### ISSUE TITLE
Document Pod Security Policies

### ISSUE THREAD

**Issue by schu** [kinvolk/lokomotive#1]
## Description

Document the PSP setup and how users can/should extend the existing policies for "optimal security".

## Initial task breakdown

- [ ] Document default PSPs (`privileged` and `restricted`)
- [ ] Give recommendations for creation and usage of PSPs

## Acceptance Criteria

- [ ] Documentation for the above tasks is deployed on the Lokomotive docs site

**Comment by johananl** [comment]
Closing in favor of https://github.com/kinvolk/lokomotive/issues/330 which is more detailed.
