### ISSUE TITLE
Consider encrypting in-cluster traffic

### ISSUE THREAD

**Issue by iaguis** [kinvolk/lokomotive#10]
Right now in-cluster traffic is unencrypted. For cases where users don't trust the network this might be problematic.

We can be solve this in different ways (using a CNI plugin with encryption support, using a service mesh...)

This issue tracks discussions on this topic.

**Comment by invidian** [comment]
This could be done experimentally with latest version of Calico (3.14+) and WireGuard.

**Comment by iaguis** [comment]
Calico 3.15 was released and supports Wireguard over VXLAN and IPIP so we could add experimental support for this once https://github.com/kinvolk/lokomotive/pull/652 is merged.

**Comment by surajssd** [comment]
The PR is close to merging.
