### ISSUE TITLE
Change the default reclaim policy of rook-ceph to Retain

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#1003]
- Change the default.
- Add a knob for user to choose what they want.

**Comment by invidian** [comment]
Why do we want to change it?

**Comment by surajssd** [comment]
It adds a safeguard against accidentally deleting the data. More like a "Do you want to delete this?" pop up of the web/desktop applications.

**Comment by invidian** [comment]
What is special about rook-ceph that we want to change it? Should we do it for all volumes we create? What about OpenEBS?

**Comment by surajssd** [comment]
Oh nothing special about rook ceph, yes we can make that Lokomotive wide default "StorageClass" setting.
