### ISSUE TITLE
List of disabled linters in .golangci.yml does not match old one from Makefile

### ISSUE THREAD

**Issue by invidian** [kinvolk/lokomotive#1024]
New list:
```
  disable:
    - exportloopref
    - gci
    - gochecknoglobals
    - godox
    - goerr113
    - goheader
    - gomodguard
    - nlreturn
    - sqlclosecheck
```

Old list:
```
--disable=gci,godox,gochecknoglobals,goerr113
```

@knrt10 why did we disable more linters as part of #812? I think they should be re-enabled.

**Comment by knrt10** [comment]
IIRC I saw them disabled by default on their website, so added them here. And yes, I think they should be re enabled. Will create a PR for it.

**Comment by invidian** [comment]
>IIRC I saw them disabled by default on their website, so added them here. And yes, I think they should be re enabled. Will create a PR for it.

Thanks! So long they do not cause annoyance (in terms of pickiness or performance), I think it does not harm to have them enabled, thanks!
