### ISSUE TITLE
CI pipeline says: `../set-terraform-version: No such file`

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#1032]
```
/deploy-test-cloud-cluster: line 97: ../set-terraform-version: No such file or directory
```

See this CI run: https://yard.lokomotive-k8s.net/builds/35981.

**Comment by invidian** [comment]
This is only for transition period between Terraform 0.12 and Terraform 0.13 and the output is harmless. Can we close it @surajssd ? The script call will be removed once #824  is merged.
