### ISSUE TITLE
In TestSelfHostedKubeletLabels test also delete kubelet pod

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#1036]
Delete the kubelet pod apart from deleting the node object. I think sometimes when we just delete the node object the register sequence never starts. And that's why we are seeing flaky tests.

I am not, sure if it is upto the kubelet to identify if it is deregistered and register again. So solving the problem who has the responsibility to fix the kubelet is out of scope of this issue.

**Comment by invidian** [comment]
I'll take care of that as it makes CI flaky.
