### ISSUE TITLE
Update our helm fork

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#1037]
Update https://github.com/kinvolk/helm to the latest with the required patches.

cc: @invidian

**Comment by invidian** [comment]
We are currently based on v3.2.1. Latest upstream is v3.3.4. @surajssd any specific patches you would like to be pulled in?

**Comment by surajssd** [comment]
I want to update the dependency of kubernetes as well. With current helm dependency it is not possible. I am hoping it will solve the linkerd issue that I see during update of 1.19.2.

**Comment by invidian** [comment]
Helm v3.3.4 still uses 0.18.8 version of client-go: https://github.com/helm/helm/blob/v3.3.4/go.mod#L39.

**Comment by surajssd** [comment]
This is updated now and we should pull the new changes: https://github.com/helm/helm/blob/v3.4.0/go.mod#L41

**Comment by invidian** [comment]
Note that `lokomotive` still use `k8s.io/api v0.18.0`. But yeah, we should be able to update now.

**Comment by invidian** [comment]
I looked at it and unfortunately rebasing the patch is not trivial and requires knowing the code changes which are included there. Perhaps @iaguis could have a look into it.

**Comment by invidian** [comment]
Assigning @knrt10, as he would like to resolve it, to make finishing #1272 easier.
