### ISSUE TITLE
Dex does not pick up updated config

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#1039]
To pick this config up someone has to kill the dex pod and then it picks it up. Either find a way to enable dex's config reload functionality. Or add a way to recreate pods when configmap is updated.

**Comment by invidian** [comment]
You can use something like this to automatically re-create pods on config change: https://github.com/flexkube/kubernetes-helm-chart/blob/master/templates/kube-scheduler/deployment.yaml#L29-L32
