### ISSUE TITLE
Add variables to AKS platfrom

### ISSUE THREAD

**Issue by knrt10** [kinvolk/lokomotive#1041]
currently, the labels added by users are not added to the Azure platform. They are not getting applied in `assets/terraform-modules/azure/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl`

**Comment by invidian** [comment]
`assets/terraform-modules/azure/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl` is not related to AKS platform. We currently have Terraform code for Azure, but it has no Go implementation.

**Comment by invidian** [comment]
I'll close it as invalid, as AKS do support node labels.
