### ISSUE TITLE
lokoctl fails to discover kubeconfig when `cluster` block is defined

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#105]
When I try to install the components defined in the `.lokocfg` file that also has cluster information (`cluster "packet" {`) then I get following error.

```console
$ lokoctl component install prometheus-operator
Installing component 'prometheus-operator'...
FATA[0000] stat assets/cluster-assets/auth/kubeconfig: no such file or directory  args="[prometheus-operator]" command="lokoctl component install"
```

```console
$ ls
lokocfg.vars  packet-cluster.lokocfg
```

I think it is trying to look for kubeconfig in the assets directory when there is none.

This error is encountered on:

```console
$ lokoctl version
1c35d016
```

But this error is not seen if there is no `cluster` block defined in the directory.

**Comment by invidian** [comment]
@surajssd is your cluster installed? I think this is intended, if you have `cluster` block defined, then we take the kubeconfig file from the assets location. If there is no `cluster` block, then we fallback to KUBECONFIG environment variable.

**Comment by surajssd** [comment]
The cluster is installed but I don't have it in this folder, in some other directory the asset exists.

**Comment by invidian** [comment]
I suggest running again `lokoctl cluster install` then, to ensure that all needed files are in place. Why would you not have this file in there?

**Comment by surajssd** [comment]
Even if we fail we should fail with an error that tells user what they have done wrong then.

**Comment by invidian** [comment]
I guess we could check if the cluster has been installed and if kubeconfig exists and give appropriate error message. And also suggest, that configuration files for cluster were found, so it will be installed on this cluster. We could also pull `kubeconfig` content from Terraform to not rely on reading the file from the disk. What do you think @surajssd ?

**Comment by invidian** [comment]
I'll close this and let's track it in #608.
