### ISSUE TITLE
Use GitHub Actions for unit tests and codespell

### ISSUE THREAD

**Issue by invidian** [kinvolk/lokomotive#1054]
It seems they are very fast and easy to configure, so it should improve contribution experience.

**Comment by knrt10** [comment]
You also liked it didn't you? 😁

**Comment by knrt10** [comment]
I can take a look into this

**Comment by invidian** [comment]
@knrt10 sure! Some pointers what I used are here: https://github.com/kinvolk/terraform-provider-tinkerbell/tree/master/.github/workflows.

I'd like actions to build, run unit tests, lint and codespell. Once we have them in place we can remove them from our CI then.
