### ISSUE TITLE
Rename all Packet references to Equinix Metal

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#1060]
Packet was renamed to Equinix Metal lately. We should update any relevant references.

Things to consider:

- We might not want to break `cluster "packet" {}`. Maybe we should support both `packet` and `equinix-metal` for a while.
- We should verify we aren't breaking links.

**Comment by ahrkrak** [comment]
LGTM, I agree with supporting both.

**Comment by iaguis** [comment]
Let's rename documentation for now.

**Comment by ipochi** [comment]
This issue has been partially fixed by addressing the documentation changes in #1537 

I'll open a new issue to track the code and config changes that are part of the PR #1545
