### ISSUE TITLE
Release v0.6.0

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#1064]
Pick me! Pick me!

**Comment by invidian** [comment]
Re-assigning as we discussed.

**Comment by invidian** [comment]
Release highlights based on skimming trough https://github.com/kinvolk/lokomotive/compare/v0.5.0...master:

Updates:
- Updated all Terraform providers to newer versions #1133
- Updated cluster-autoscaler to version v1.1.0 #1137
- Updated contour to v1.10.0 #1170
- Updated Rook to v1.4.6 #1117
- Updated Velero to v1.5.2 #1131
- Updated AWS EBS CSI Driver to v0.7.0 #1135
- Updated OpenEBS to v2.2.0 #1095
- Updated Kubernetes version to v1.19.4 #1189
- Updated Kubernetes version on AKS to v1.18.10 #1189
- Updated used Go version to 1.15.4 #1190
- Updated LinkerD to stable-2.9.0 #1123
- Updated prometheus-operator to 0.43.2 #1162
- Updated Web UI to v0.1.3 #1237

Enhancements:
- Bootkube will now wait for all controlplane charts to converge before exiting, which should make bootstrapping process more stable #1085
- cluster-autoscaler: improved detecting duplicated devices, which should fix installing cluster-autoscaler component when one is using Project API key #1168
- If bootkube run fails to bootstrap the cluster, it's logs will be printed by Terraform and `lokoctl` which makes debugging of such failures easier #1166
- calico-hostendpoint-controller is now allowed to run on controller nodes, which makes cluster bootstrapping independent from available worker nodes, which should make bootstrapping process faster #1180
- Improved validation rules for Hardware Reservation IDs on Packet, which should result in less surprising behavior #1186
- Pin CoreDNS version to 1.8.0 to ensure running version consistency #1203
- Switched cluster Docker images using Docker Hub to use Quay.io to mitigate Docker Hub pulling limits to make cluster bootstrapping more reproducible #1226
- Controlplane components configuration will now be reverted to last good state before we attempt upgrade to make upgrades more reproducible 466b4658b6e5e9ff095a56159a0b5ad8b49bc285
- TLS bootstrap secrets will be now updated as first component to give more time for nodes to join before verification phase 57d771c

Bug fixes:
- Nodes health will now be verified _after_ upgrading controlplane components to allow updating TLS bootstrap secrets. This fixes adding new worker pools when TLS bootstrap is enabled e06bfab
- Fixed controlplane components running on DaemonSet on single controlplane node clusters #1193

Testing:
- Added basic e2e tests for Rook Ceph #1084
- Added basic e2e tests for FLUO #1142

Documentation:
- Added OpenEBS upgrade guide #1163
- Added Rook Ceph upgrade guide #1165

New features:
- Added support for Tinkerbell platform #392
- Exposed --conntrack-max-per-core kube-proxy flag, which might be useful for cluster handling large number of connections #1187
- Exposed Envoy metrics scraping interval in Contour, which should improve detecting latency spikes for latency-sensitive workloads #1229
- Packet is now using CCM. CCM is responsible for enabling BGP session on devices and for removing Node objects which do not have associated Packet device #1155

**Comment by iaguis** [comment]
WIP branch for this: https://github.com/kinvolk/lokomotive/commits/iaguis/v0.6.0-pre

cc @surajssd

**Comment by knrt10** [comment]
https://github.com/kinvolk/lokomotive/releases/tag/v0.6.0
