### ISSUE TITLE
etcd systemd unit should wait for certificate files to become available

### ISSUE THREAD

**Issue by invidian** [kinvolk/lokomotive#1066]
Otherwise etcd start right after booting and fails several time before we copy certificates over SSH, then it converges.

This produces logs like:
```
Oct 12 13:14:07 tink-controller-0 96c53009bb40[846]: 2020-10-12 13:14:07.754655 I | etcdmain: etcd Version: 3.4.13
Oct 12 13:14:07 tink-controller-0 96c53009bb40[846]: 2020-10-12 13:14:07.754682 I | etcdmain: Git SHA: ae9734ed2
Oct 12 13:14:07 tink-controller-0 96c53009bb40[846]: 2020-10-12 13:14:07.754692 I | etcdmain: Go Version: go1.12.17
Oct 12 13:14:07 tink-controller-0 96c53009bb40[846]: 2020-10-12 13:14:07.754967 I | etcdmain: Go OS/Arch: linux/amd64
Oct 12 13:14:07 tink-controller-0 96c53009bb40[846]: 2020-10-12 13:14:07.755005 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
Oct 12 13:14:07 tink-controller-0 96c53009bb40[846]: [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
Oct 12 13:14:07 tink-controller-0 96c53009bb40[846]: 2020-10-12 13:14:07.755325 I | embed: peerTLS: cert = /etc/ssl/etcd/etcd/peer.crt, key = /etc/ssl/etcd/etcd/peer.key, trusted-ca = /etc/ssl/etcd/etcd/peer-ca.crt, client-cert-auth = true>
Oct 12 13:14:07 tink-controller-0 96c53009bb40[846]: 2020-10-12 13:14:07.755756 C | etcdmain: open /etc/ssl/etcd/etcd/peer.crt: no such file or directory
```

And adds unnecessary noise tot he system.

**Comment by pothos** [comment]
`assets/terraform-modules/controller/templates/etcd.yaml.tmpl` has this already added a day after this issue got created:

```
        ConditionPathExists=/etc/ssl/etcd/etcd/server-ca.crt
        ConditionPathExists=/etc/ssl/etcd/etcd/server.crt
        ConditionPathExists=/etc/ssl/etcd/etcd/server.key
        ConditionPathExists=/etc/ssl/etcd/etcd/peer-ca.crt
        ConditionPathExists=/etc/ssl/etcd/etcd/peer.crt
        ConditionPathExists=/etc/ssl/etcd/etcd/peer.key
```
It's just a matter of aligning the remaining platforms to use this.

**Comment by invidian** [comment]
>It's just a matter of aligning the remaining platforms to use the common controller/worker modules.

I wouldn't say "just", but yeah :smile:

**Comment by pothos** [comment]
Ported the conditions over in https://github.com/kinvolk/lokomotive/pull/1511

**Comment by invidian** [comment]
Hmm, it seems #1511 does not work as expected. See https://yard.lokomotive-k8s.net/builds/4690979 :disappointed:

**Comment by iaguis** [comment]
Those conditions weren't doing anything because [they have to be specified in the `[Unit]` section](https://manpages.debian.org/stretch/systemd/systemd.unit.5.en.html#DESCRIPTION).

**Comment by pothos** [comment]
Good find^^ In `assets/terraform-modules/controller/templates/etcd.yaml.tmpl` they are also under `[Service]`.

**Comment by iaguis** [comment]
I'll file a PR fixing them everywhere. I hope this doesn't break things :sweat_smile:
