### ISSUE TITLE
Prevent deleting of component namespace if any other release object exists in this namespace

### ISSUE THREAD

**Issue by knrt10** [kinvolk/lokomotive#1077]
### Problem Statement

Currently, if the user has more than 1 component installed in same namespace and they try to delete a single component using **delete-namespace** flag, it does no checks and deletes the namespace. This issue occured as **headlamp** component is installed in **lokomotive-system** namespace. And deleting it will result in the deletion of **admission-webhook.**

### Offline discussion suggestions

We wanted a solution where we can install multiple components in same namespace.

- Install these components in dedicated namespace
- Track components installed in cluster
- Check if namespace is `lokomotive-system` and throw error to user
- Create a Validation webhook and avoid deletion of `lokomotive-system` namespace
- Check if other helm release are installed in that namespace, if not delete the namespace **(accepted soultion)**

**Comment by invidian** [comment]
One more option was:
- Only remove the namespace if it has no resources left, but that would require iterating over all resources reported by `kubectl api-resources --namespaced=true` which would probably be slow and maybe even problematic from API point of view.
