### ISSUE TITLE
Update components of Lokomotive 

### ISSUE THREAD

**Issue by knrt10** [kinvolk/lokomotive#1079]
Update following components and terraform providers

| Done | Component            | Current Version      | Latest Version | Issue| PR   |
|------|----------------------|----------------------|----------------|------|------|
|   | `prometheus-operator` | `0.41.0`              | `v0.43.0`       |      | #1162 |
|   :heavy_check_mark:  | `calico`             | `v3.15.2`            | `v3.16.4`      |        | #1113 |
|   :heavy_check_mark:  | `cert-manager`       | `v0.16.1`            | `v1.0.3`      |      |  #1114  |
|   :heavy_check_mark:  | `contour`       | `v1.7.0`            | `v1.9.0`      |      | #1136  |
|   :heavy_check_mark:  | `external-dns`       | `0.7.3`             | `0.7.4`        |      | #1115 |
|   :heavy_check_mark:   | `metrics-server`               | `2.11.1`             | `2.11.2`       |       | #1116 |
|   :heavy_check_mark:   | `openebs`               | `1.12.3`             | `2.2.0`       |       |  #1095 |
|  :heavy_check_mark: | `rook` | `v1.4.2`              | `v1.4.6`       |      | #1117 |
| :heavy_check_mark:  | `aws-ebs-csi-driver` | `0.6.0`              | `v0.7.0`       |      | #1135 |
|   :heavy_check_mark:     | `velero`             | `1.4.2`              | `1.5.2`      |     | #1131 |
|  :heavy_check_mark: | `cluster-autoscaler` | `1.0.2`             | `1.1.0`       |      | #1137 |
|  :heavy_check_mark: | `experimental-istio-operator` | `1.6.3`             | `1.7.3`       |      | #1086 |

| Done | TF Provider | Current Version | Latest Version | Issue| PR   |
|------|-------------|-----------------|----------------|------|------|
|   :heavy_check_mark:  | AWS         | `v3.3.0`        | `v3.10.0`       |      | #1133  | 
|   :heavy_check_mark:   | Azure       | `1.35.0`        | `v2.31.1`      |       | #1133 | 
|    :heavy_check_mark:  | Local       | `v1.4.0`           | `v2.0.0`       |       | #1133 | 
|   :heavy_check_mark:  | Null        | `2.1.2`           | `v3.0.0`       |      | #1133 |

**Comment by invidian** [comment]
etcd update is false-positive. Same for MetalLB

**Comment by knrt10** [comment]
Updated description

**Comment by surajssd** [comment]
Rook is added twice :thinking:

**Comment by ipochi** [comment]
updated OpenEBS to 2.2.0 in #1095

**Comment by knrt10** [comment]
Working on `aws-ebs-csi-driver`

**Comment by ipochi** [comment]
> Working on `aws-ebs-csi-driver`

negative. Sorry I had created branch of it last week. Forgot to push.

**Comment by knrt10** [comment]
No worries, working on `contour` then 😄

**Comment by knrt10** [comment]
working on `cluster-autoscaler`

**Comment by invidian** [comment]
Last remaining PR to merge is #1162

**Comment by ipochi** [comment]
Latest update:
https://github.com/kinvolk/lokomotive/pull/1162#issuecomment-732179755
