### ISSUE TITLE
--kubeconfig-flag does not work for "component apply" since 8fa88dae

### ISSUE THREAD

**Issue by invidian** [kinvolk/lokomotive#1094]
Surprisingly, it works for "component delete"...

**Comment by knrt10** [comment]
Should we add this in 0.5.0?

**Comment by invidian** [comment]
>Should we add this in 0.5.0?

@iaguis ?

**Comment by invidian** [comment]
#1018 will fix it, perhaps it could be isolated from this PR, but it is easier to fix this way.

**Comment by iaguis** [comment]
> Should we add this in 0.5.0?

Yes.
