### ISSUE TITLE
configmaps "extension-apiserver-authentication" is forbidden

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#1096]
kube-scheduler constantly logs the following:

```
E1019 11:57:21.407120       1 reflector.go:127] k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:kube-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
E1019 11:57:57.428130       1 reflector.go:127] k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:kube-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
E1019 11:58:31.721129       1 reflector.go:127] k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:kube-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
E1019 11:59:20.845730       1 reflector.go:127] k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:kube-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
```

I'm not sure if this is an indication for a real problem, but anyway we probably want to either fix the problem or eliminate the unnecessary logging.

Observed with lokoctl `v0.4.1-207-gd814fcc0` on Packet.

**Comment by invidian** [comment]
Perhaps `extension-apiserver-authentication-reader` role should be assigned.

**Comment by niels-s** [comment]
I wanted to report the same issue, it's producing quite some logs, and I wonder if this means something is broken?

**Comment by invidian** [comment]
@niels-s I'm not aware on any breakage caused by this. I think it might occur if you would combine it with scenario of multiple tiers of API servers, which is used in GCP IIRC, which obviously we don't use in Lokomotive.

**Comment by knrt10** [comment]
I don't think this should happen now, we have added this via ccm in https://github.com/kinvolk/lokomotive/blob/2e7f69625331d5c23ca3c20d16f56fe3fb892fcb/assets/charts/control-plane/packet-ccm/templates/deployment.yaml#L159-L170

**Comment by invidian** [comment]
@knrt10 this binding is for the CCM, we need a separate binding for kube-scheduler (and possibly other workloads which use it).

**Comment by invidian** [comment]
Did we check if other components do not suffer for the same issue?

**Comment by knrt10** [comment]
Let me confirm
