### ISSUE TITLE
Address concerns for the DNS abstraction

### ISSUE THREAD

**Issue by iaguis** [kinvolk/lokomotive#11]
We added DNS abstraction to support different DNS providers instead of just Route53. However, there were some concerns about it not being generic enough because it's not a portable Terraform target.

This issue tracks those concerns.

**Comment by ipochi** [comment]
@iaguis 

The context is missing here with `some concerns` but they haven't been mentioned here.
Also @johananl added cloudfare support for DNS, was there any more work done to improve the abstraction ?

Shall we close this or would you be open to adding a comment on the said concerns ?

**Comment by iaguis** [comment]
It seems to me this can be closed now. Let's do that.
