### ISSUE TITLE
MetalLB: BGP labels don't update on node replacement

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#1126]
When replacing a node which runs MetalLB, the k8s node labels used for peer autodiscovery aren't being updated. The reason for this is apparently the fact that we replace the server underneath the node but keep the `Node` object. When the kubelet on the new machine re-registers with the API, the values in the `--node-labels` kubelet flag aren't used again.

Once https://github.com/kinvolk/lokomotive/issues/548 is merged we can get rid of the `--node-labels` workaround and instead have the Packet CCM apply (and hopefully update) annotations with BGP information.

**Comment by invidian** [comment]
>When replacing a node which runs MetalLB, the k8s node labels used for peer autodiscovery aren't being updated. The reason for this is apparently the fact that we replace the server underneath the node but keep the Node object. When the kubelet on the new machine re-registers with the API, the values in the --node-labels kubelet flag aren't used again.

Hmm, nodes should de-register itself via systemd unit as part of host kubelet shutting down. Maybe this part is flaky somehow?
