### ISSUE TITLE
lokoctl does not remove a node and create a new one if reservation ids change

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#1156]
A worker pool was deployed with following config:

```tf
worker_pool "ingress" {
  count     = 2
  node_type = "c3.small.x86"

  reservation_ids = {
    worker-0 = "81b3d690-2f09-43ea-8854-55dab2375f82",
    worker-1 = "1df2b140-ee1b-4f6f-ab10-4b871dc5570c",
  }
}
```

Now I wanted to rotate a node as in I provided new reservation id and did a `lokoctl cluster apply` on following config:

```tf
worker_pool "ingress" {
  count     = 2
  node_type = "c3.small.x86"

  reservation_ids = {
    worker-0 = "81b3d690-2f09-43ea-8854-55dab2375f82",
    // worker-1 = "1df2b140-ee1b-4f6f-ab10-4b871dc5570c",
    worker-2 = "e80b31af-9eb4-41c8-a8ba-3f38f83d5d2d",
  }
}
```

But no new node was created after this. I expected the lokoctl to pick up the changed reservation id and create a new node and delete the old node.

**Comment by niels-s** [comment]
fyi when I was looking into the terraform code of these nodes I noticed the naming convention of the hardware reservations needs to be sequential so could be since I skipped a number this caused issues. But even when I did rename to `worker-1` it still failed for some unexplained reason.

**Comment by invidian** [comment]
I've tried the following configuration:
```hcl
  worker_pool "pool-1" {
    count     = var.workers_count
    node_type = var.workers_type

    reservation_ids = {
      worker-0 = "92ccb466-5fe6-4021-b8d8-c838dac63385"
      worker-1 = "fe84e6c3-e6d8-4b0a-b5e5-ee4ce61aa5ab"
    }
  }
```

Then made the following change:
```diff
  worker_pool "pool-1" {
    count     = var.workers_count
    node_type = var.workers_type

    reservation_ids = {
      worker-0 = "92ccb466-5fe6-4021-b8d8-c838dac63385"
-     worker-1 = "fe84e6c3-e6d8-4b0a-b5e5-ee4ce61aa5ab"
+     worker-1 = "fe84e6c3-e6d8-4b0a-b5e5-ee4ce61aa5ac"
    }
  }
```

And `lokoctl cluster apply` properly shows a Terraform plan when it tries to replace a 2nd node.

>But no new node was created after this. I expected the lokoctl to pick up the changed reservation id and create a new node and delete the old node.

@surajssd what do you mean by "no new node was created after this"? Do you mean Terraform plan was empty? Are you sure you changed the configuration properly?

#

>fyi when I was looking into the terraform code of these nodes I noticed the naming convention of the hardware reservations needs to be sequential so could be since I skipped a number this caused issues. But even when I did rename to worker-1 it still failed for some unexplained reason.

The following change:
```diff
  worker_pool "pool-1" {
    count     = var.workers_count
    node_type = var.workers_type

    reservation_ids = {
      worker-0 = "92ccb466-5fe6-4021-b8d8-c838dac63385"
-     worker-1 = "fe84e6c3-e6d8-4b0a-b5e5-ee4ce61aa5ab"
+    //worker-1 = "fe84e6c3-e6d8-4b0a-b5e5-ee4ce61aa5ab"
      worker-2 = "fe84e6c3-e6d8-4b0a-b5e5-ee4ce61aa5ac"
    }
  }
```

Indeed causes Terraform to print empty plan. This indeed seems like a bug, as in such case, I'd expect Terraform to plan re-creation of the node without hardware reservation. But in the first place, `lokoctl` should complain, that reservations are not sequential.

2 actions points here:
- Investigate why emptying `hardware_reservation_id` field does not trigger device re-creation on Packet Terraform provider side. I also checked replacing `""` with `null` in Terraform code, which gives the same result (empty plan).
- Improve validation rules around reservation IDs to give a clear error in such cases.

**Comment by invidian** [comment]
Reported https://github.com/packethost/terraform-provider-packet/issues/289 and will investigate it now.

**Comment by invidian** [comment]
Okay, so I looked at https://github.com/packethost/terraform-provider-packet/issues/289 and it seems issue there is not trivial to resolve.

However, we don't need to resolve it to resolve this bug on our side, as:
- 2nd configuration posted by @surajssd it not a valid Lokomotive configuration, we need to improve validation rules as mentioned above.
- We do not support mixing hardware reservation with on-demand instances. This mean empty reservation ID should trigger validation error.
- Emptying reservation ID should result in removing the instance.
- Changing reservation ID should replace the node as it is happening already.

**Comment by invidian** [comment]
Created #1186, which improves our validation rules, which should prevent hitting this issue.
