### ISSUE TITLE
Disable plain http for Grafana ingress

### ISSUE THREAD

**Issue by niels-s** [kinvolk/lokomotive#1195]
**Current situation**
When deploying the prometheus-operator component with a public Grafana ingress the ingress is still accessible over plain HTTP even when HTTPS is available.

```
component "prometheus-operator" {
  grafana {
    ...
    ingress {
      host = "grafana.example.com"
    }
  }
  ...
}
```

**Impact**

**Ideal future situation**
Plain HTTP traffic is disabled and all traffic is redirected to HTTPS instead

**Implementation options**

We can use the ingress annotation supported by Project Contour to disable HTTP and force HTTPS
- `ingress.kubernetes.io/force-ssl-redirect: "true"`
- `kubernetes.io/ingress.allow-http: "false"`

**Additional information**
I've applied the annotations myself on our cluster running Lokomotive v0.4.1. But I wasn't able to get the expected result.
When applying the `ingress.kubernetes.io/force-ssl-redirect: "true"`  annotation that resulted in the browser getting stuck in an `ERR_TOO_MANY_REDIRECTS` loop. However, I couldn't find any immediate errors in the envoy logs.
When I applied the `kubernetes.io/ingress.allow-http: "false"` annotation the ingress stop working entirely and the service wasn't accessible anymore

**Comment by invidian** [comment]
Hmm, perhaps this should be handled together with #808.

**Comment by niels-s** [comment]
Seems like this ticket is a duplicate then, my apologies, should have searched first. I'll close this one in favor of #808

**Comment by invidian** [comment]
>Seems like this ticket is a duplicate then, my apologies, should have searched first. I'll close this one in favor of #808

No worries, I planned to keep this issue open, as it's Grafana-specific while #808 is a generic issue, but closing it is fine as well :)

**Comment by surajssd** [comment]
I tried on both AWS and Packet and I wasn't able to create the `ERR_TOO_MANY_REDIRECTS` issue.

Although I see following in the contour controller pods, might as well be unrelated to current issue:

```
time="2020-11-19T09:49:25Z" level=info msg="handling v3 xDS resource request" connection=3 context=xds node_id=envoy-jpbbc node_version=v1.16.0 resource_names
="[]" response_nonce=18 type_url=type.googleapis.com/envoy.config.listener.v3.Listener version_info=18
```

**Comment by surajssd** [comment]
Just adding the annotation worked for `httpbin` component and Grafana ingress both.
