### ISSUE TITLE
script/find-update needs to be updated

### ISSUE THREAD

**Issue by knrt10** [kinvolk/lokomotive#1209]
**Description**

Helm stable repo has [been deprecated](https://github.com/helm/charts#%EF%B8%8F-deprecation-and-archive-notice) and some components like [metrics server ](https://github.com/helm/charts/tree/master/stable/metrics-server)have deprecated their chart. There is [ongoing work](https://github.com/kubernetes-sigs/metrics-server/pull/606) to move the chart to their repo. Once merged then this issue can be fixed.

**Impact**

Update script does not work

**Environment and steps to reproduce**

1. run `script/find-updates.sh`

**Expected behavior**
It should work

**Additional information**
It will fail on metrics-sever component with error `Error: failed to fetch https://charts.helm.sh/stable/metrics-server-2.11.4.tgz : 404 Not Found`

**Comment by invidian** [comment]
>It will fail on metrics-sever component with error

The repo is still available if you use the following command: `helm repo add stable https://charts.helm.sh/stable`. So I re-labeled the issue.
