### ISSUE TITLE
Clusterroles not found for kube-scheduler

### ISSUE THREAD

**Issue by knrt10** [kinvolk/lokomotive#1253]
**Description**

We have clusterrolebindings for `kube-scheduler` but no cluster roles created for them. This throw error

```sh
clusterrole.rbac.authorization.k8s.io "restricted-psp" not found, clusterrole.rbac.authorization.k8s.io "system:basic-user" not found, clusterrole.rbac.authorization.k8s.io "system:discovery" not found, clusterrole.rbac.authorization.k8s.io "system:public-info-viewer" not found, clusterrole.rbac.authorization.k8s.io "system:kube-scheduler" not found, clusterrole.rbac.authorization.k8s.io "system:volume-scheduler" not found, clusterrole.rbac.authorization.k8s.io "privileged-psp" not found
```

**Environment and steps to reproduce**

1. Run a single node cluster
2. Check logs for kube-scheduler, `kubectl logs kube-scheduler-845bddddfd-db9j4 -f`

**Expected behavior**
No errors.

**Additional information**

![Screenshot 2020-12-07 at 7 15 05 PM](https://user-images.githubusercontent.com/24803604/101358319-b2d34a80-38c0-11eb-802b-71df4db151a0.png)

**Comment by surajssd** [comment]
@knrt10 where did you see the error:

```
clusterrole.rbac.authorization.k8s.io "restricted-psp" not found,
clusterrole.rbac.authorization.k8s.io "system:basic-user" not found,
clusterrole.rbac.authorization.k8s.io "system:discovery" not found,
clusterrole.rbac.authorization.k8s.io "system:public-info-viewer" not found,
clusterrole.rbac.authorization.k8s.io "system:kube-scheduler" not found,
clusterrole.rbac.authorization.k8s.io "system:volume-scheduler" not found,
clusterrole.rbac.authorization.k8s.io "privileged-psp" not found
```

**Comment by knrt10** [comment]
when I ran logs for `kube-scheduler`

**Comment by surajssd** [comment]
The only errors I am seeing in my cluster are https://gist.github.com/surajssd/6845f354d944ea264ff0cb89692bd359

Above was generated by running `k logs kube-scheduler-845bddddfd-khshb | grep ^E | gh gist create -`.

**Comment by knrt10** [comment]
Can you grep for `authentication.go:294`?

**Comment by surajssd** [comment]
@knrt10 

```console
$ k logs kube-scheduler-845bddddfd-khshb | grep 'authentication.go:294'
W1207 09:16:25.466682       1 authentication.go:294] Error looking up in-cluster authentication configuration: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:kube-scheduler" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
```

**Comment by knrt10** [comment]
I am creating a cluster again, let's see if I get the error. If yes, I will setup gangway for you to confirm. If not, I will close this issue. Cool?

**Comment by knrt10** [comment]
Not able to reproduce, so closing this
