### ISSUE TITLE
Add component or platform to lokomotive

### ISSUE THREAD

**Issue by jbanety** [kinvolk/lokomotive#1312]
Hi,

Is there a way to add component or platform to lokomotive without compiling it ?

Thanks for your great work !

**Comment by surajssd** [comment]
@jbanety ATM, the only way to add a platform or component is by compiling it.

**Comment by jbanety** [comment]
OK.
I'm already patching the source code to apply my modification.
Is this planned ?

**Comment by surajssd** [comment]
@jbanety we have played with the idea of custom components. But for platforms it is more tricky and hard to get right. Not promising anything right now though.

If you have specific use case please let us know. :slightly_smiling_face:

**Comment by invidian** [comment]
@jbanety I will create a separate issue for custom component concept, as other people are also interested in it. Will CC you there :)

**Comment by jbanety** [comment]
@surajssd I'm creating components I'm already using in production (e.g. Linstor/DRBD storage) to automate cluster creation or scaling.    
For platforms, I'm using bare metal servers hosted at OVH. Some tweaks are needed to boot on iPXE, ...    
Currently I'm using a couple of Bash scripts with lokoctl to deploy a VM with matchbox, modify servers boot option depending Ignition state.    
I have modified baremetal platform and terraform module to allow utilizing all options offered by terraform modules (e.g. customizing etcd servers, api servers ips, ...) I'll create a PR when it will pass my QA tests.

**Comment by invidian** [comment]
Created #1321 as an umbrella issue to track the efforts on custom components support.
