### ISSUE TITLE
Packet: using n2.xlarge.x86 plan results in error "Strange 2-bond ports conf"

### ISSUE THREAD

**Issue by displague** [kinvolk/lokomotive#1346]
**Description**

v3.0.1 of the Packet provider does not detect the network type correctly on device plans with more than two network ports (n2.xlarge.x86). Due to a recent change in the API, when deploying a network type of "layer3", this version of the provider returns an error message: "Strange 2-bond ports conf - bond0: layer3, bond1: layer2-bonded".

The latest Packet provider is v3.2.1. Version 3.0.1 of the provider is currently templated by lokoctl.  These two versions of generally compatible.

(The Equinix Metal provider v1.0.0 is mostly the same as v3.2.1, but the resource names and state would need to be renamed. Managing the migration could be tricky. https://github.com/equinix/terraform-provider-metal/issues/1)

**Impact**

Updating the Packet provider to v3.2.1. will fix support for 4 port devices on Packet.

**Environment and steps to reproduce**

1. **Set-up**:  Packet / n2.xlarge.x86
2. **Task**: `lokoctl cluster apply`
3. **Action(s)**: 
  a. External factors (API was updated)
4. **Error**: `Strange 2-bond ports conf - bond0: layer3, bond1: layer2-bonded`

**Expected behavior**

No error.

**Additional information**

Related to https://github.com/packethost/terraform-provider-packet/issues/306

**Comment by invidian** [comment]
Fixed in #1349 I believe.
