### ISSUE TITLE
Lokoctl reinstalls kube-proxy and much of control-plane on every update

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#1367]
The "Ensuring controlplane component ..." step installs the kube-proxy and some other control plane component every time you run `lokoctl cluster apply --skip-components`. For a large enough cluster this is time consuming and very slow. Especially if the `lokoctl cluster apply --skip-components` command fails for some reason and user has to run the command again.

"Ensuring" should just ensure instead of doing update every time.

**Comment by invidian** [comment]
>The "Ensuring controlplane component ..." step installs the kube-proxy and some other control plane component every time you run lokoctl component update. For a large enough cluster this is time consuming and very slow. Especially if the lokoctl cluster apply command fails for some reason and user has to run the command again.

This seems odd. The only thing which should be happening is re-installation of last Helm release for `kube-proxy`, which assuming no changes on the cluster has been made externally, should be very quick.

What kind of slowness and cluster events do you observe when this is happening? Do you use some external software to modify `kube-proxy` configuration?

As a workaround, you can also use `--skip-pre-update-health-check`, which will skip running those health checks.

**Comment by invidian** [comment]
>`lokoctl component update`

Wait, does it run for `lokoctl component update`? Really? This is clearly a bug then.

**Comment by surajssd** [comment]
Oops I meant, `lokoctl cluster apply`. Editing the description.

**Comment by pothos** [comment]
I also have this problem when creating a cluster and the first run has a provisioning failure, and the second run (with `--skip-pre-update-health-check`) now thinks that because `exists` is true, it needs to run this:
```
        // Do controlplane upgrades only if cluster already exists and it is not a managed platform.
        if exists && !c.platform.Meta().Managed {
```
Knowing whether the cluster "exists" is maybe a bit tricky, but it would at least be good to have a flag to disable this, similar to `--skip-pre-update-health-check`.

**Comment by invidian** [comment]
>I also have this problem when creating a cluster and the first run has a provisioning failure, and the second run (with --skip-pre-update-health-check) now thinks that because exists is true, it needs to run this:

Yeah. If provisioning fails, the best thing to do right now it to tear everything down and start from scratch.

**Comment by pothos** [comment]
I think it would be good to have an option to suppress the control plane updates.

**Comment by invidian** [comment]
Perhaps. Can you open separate issue for it?

**Comment by surajssd** [comment]
Maybe this is not a case now.
