### ISSUE TITLE
Bring back Baremetal module changes

### ISSUE THREAD

**Issue by meyskens** [kinvolk/lokomotive#1427]
**Current situation**
In https://github.com/kinvolk/lokomotive/pull/1426 we reverted several changes inside the codebase to make the upgrade processes of the baremetal module possible without breaking etcd and the api server or having an extensive upgrade process for baremetal users.

The reason for this is the endpoints changing causing all certificates need updating with new DNS SANs.

**Impact**
This reverted 5 PRs with changes

**Ideal future situation**
After certificate rotation #309 and #1201 is implemented this can be used to rotate the certificates on update for both Kubernetes and etcd. After this the PRs can be put back and an upgrade process be tested and documented.

**Comment by iaguis** [comment]
These changes were all brought back.
