### ISSUE TITLE
Use spot instances for CI tests on AWS

### ISSUE THREAD

**Issue by blixtra** [kinvolk/lokomotive#149]
We run CI quite often. On AWS, spot instances can be used to save costs. In most cases, this will be exactly like running with on-demand instances.

We will probably have to introduce some logic to detect if the test ends due to getting terminated and then restart the test in another region or with different instance types. But I would prose making the change without that logic to start with.

**Comment by invidian** [comment]
I think we should re-open and also do it for controller nodes.

**Comment by iaguis** [comment]
As a feature, I'm on the fence about whether enabling spot instances for controller nodes makes sense, we can open an issue to discuss.

**Comment by iaguis** [comment]
https://github.com/kinvolk/lokomotive/issues/174

**Comment by blixtra** [comment]
> As a feature, I'm on the fence about whether enabling spot instances for controller nodes makes sense, we can open an issue to discuss.

I can understand that for prod clusters, but for CI tests that should surely be ok, right?
