### ISSUE TITLE
Investigate CI failures

### ISSUE THREAD

**Issue by ipochi** [kinvolk/lokomotive#1496]
Of late, we are noticing a lot more CI failures.  Failures including etcd and bootkube servce failures, certification rotation tests not passing. Re-running the CI usually makes the CI passes but its usually more than one triggers.

While CI getting green is a good indication that that the tests maybe be flaky in nature or network related issues or some unknown cause, the fact of the matter is that we don't know the cause and it would be good to investigate and fix not only for CI but also the reliability of Lokomotive.

Few CI failures are linked below:

https://yard.lokomotive-k8s.net/teams/main/pipelines/pr-packet-arm/jobs/test-lokomotive-packet-deployment/builds/2742
https://yard.lokomotive-k8s.net/teams/main/pipelines/pr-aws/jobs/test-lokomotive-aws-deployment/builds/1798.3
https://yard.lokomotive-k8s.net/teams/main/pipelines/pr-aws/jobs/test-lokomotive-aws-deployment/builds/1798.2
https://yard.lokomotive-k8s.net/teams/main/pipelines/pr-bare-metal/jobs/test-lokomotive-deployment/builds/2792
https://yard.lokomotive-k8s.net/teams/main/pipelines/pr-bare-metal/jobs/test-lokomotive-deployment/builds/2779.1
https://yard.lokomotive-k8s.net/teams/main/pipelines/pr-packet-arm/jobs/test-lokomotive-packet-deployment/builds/2742
https://yard.lokomotive-k8s.net/builds/3977070
https://yard.lokomotive-k8s.net/builds/3977078

**Comment by surajssd** [comment]
Meanwhile ARM pipeline has been failing consistently with the following error:

```
module.packet-ci1623653457-kx.null_resource.copy-controller-secrets[0]: Still creating... [59m39s elapsed]
module.packet-ci1623653457-kx.null_resource.copy-controller-secrets[0]: Still creating... [59m49s elapsed]
module.packet-ci1623653457-kx.null_resource.copy-controller-secrets[0]: Still creating... [59m59s elapsed]


Error: timeout - last error: dial tcp 147.75.93.162:22: i/o timeout


FATA[3876] Applying cluster failed: applying platform: failed checking execution status: exit status 1  args="[]" command="lokoctl cluster apply"
+ RET=1
```

**Comment by surajssd** [comment]
This [AWS failure](https://yard.lokomotive-k8s.net/teams/main/pipelines/pr-aws/jobs/test-lokomotive-aws-deployment/builds/1798.3) due to dex is taken care of in [this commit](https://github.com/kinvolk/lokomotive/pull/1487/commits/7ec213e8df51ba95cbbf9b7fd4b43b8dc611f877) of  PR https://github.com/kinvolk/lokomotive/pull/1487.

**Comment by pothos** [comment]
Another thing is that the etcd service restart for the controller secrets fails often:
```
docker: Error response from daemon: Conflict. The container name "/etcd" is already in use by container "80de770a5b5ae72c4339e722e56575a500ab48a6eb60823d2001db4283d83f7f". You have to remove (or rename) that container to be able to reuse that name.
```
Seems to be a race when the Docker daemon did not full clean up the old one…

**Comment by pothos** [comment]
Actually there was a problem with concurrent etcd container restarts, filed a PR for that in https://github.com/kinvolk/lokomotive/pull/1511

**Comment by iaguis** [comment]
We've fixed most pressing issues in the CI. Let's open issues for specific problems. Closing this.
