### ISSUE TITLE
New component for onboarding a Lokomotive cluster in Azure Arc

### ISSUE THREAD

**Issue by ipochi** [kinvolk/lokomotive#1497]
Currently a Lokomotive user can follow steps outlined in Azure Arc docs to onboard a Lokomotive cluster to Azure Arc.

I believe we can simply the process a little bit but integrating the onboarding and removing process of a Lokomotive cluster in Azure Arc as a Lokomotive component.

This would be a initial use case of the component which can later encompass further use cases and more tighter integration.

**Comment by surajssd** [comment]
@ipochi can we close this one?

**Comment by ipochi** [comment]
Closing as the corresponding PR for the component was merged 
#1473
