### ISSUE TITLE
[RFE] Add tolerations to Prometheus Operator

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#1527]
Currently prometheus-operator only supports `nodeSelectors` or `nodeAffinity` but not tolerations. Add them to the `prometheus-operator` component.

**Comment by knrt10** [comment]
@surajssd to confirm which tolerations do we want? For `Prometheus` config or `component` config i.e `PrometheusOperatorTolerations`

**Comment by surajssd** [comment]
@knrt10 we should support all of the following (these are JSON paths of the prometheus-operator component values file):

```
prometheusOperator.tolerations
prometheusOperator.admissionWebhooks.patch.tolerations
alermanager.alermanagerSpec.tolerations
prometheus.prometheusSpec.tolerations
```
