### ISSUE TITLE
Broken link on https://kinvolk.io/docs/lokomotive/0.8/how-to-guides/ingress-with-contour-metallb/

### ISSUE THREAD

**Issue by ericlake** [kinvolk/lokomotive#1551]
The link at https://kinvolk.io/docs/lokomotive/0.8/how-to-guides/ingress-with-contour-metallb/#prerequisites for `Public Elastic IPs` is broken. It currently links to https://support.equinixmetal.com/kb/articles/elastic-ips which does not exist. Possibly it should link to https://metal.equinix.com/developers/docs/networking/elastic-ips/#elastic-ip-addresses instead.

**Comment by iaguis** [comment]
Thanks! This should be fixed by https://github.com/kinvolk/lokomotive/pull/1537 too.
