### ISSUE TITLE
Broken link on https://kinvolk.io/docs/lokomotive/latest/concepts/packet/

### ISSUE THREAD

**Issue by ericlake** [kinvolk/lokomotive#1552]
https://kinvolk.io/docs/lokomotive/latest/concepts/packet/ has a link that is meant to point to `Flatcar Container Linux Customization` but this results in a 404.

**Comment by iaguis** [comment]
Thanks for reporting! This should be fixed by https://github.com/kinvolk/lokomotive/pull/1537 (in this commit: https://github.com/kinvolk/lokomotive/commit/05ce568bc5c32fd919c4a2a08cea0c0afcff63fd) and will reflect on the website when we release v0.9.0.
