### ISSUE TITLE
Single node test deployment.

### ISSUE THREAD

**Issue by ajrpayne** [kinvolk/lokomotive#1572]
Looking at the website docs. https://kinvolk.io/docs/lokomotive/latest/configuration-reference/platforms/baremetal/

I don't see a option in baremetalcluster.lokocfg reference for creating a single node cluster.

If I leave the worker_* variables out will it deploy a single node? Do I fill in the worker_* variables with the same info that will be in the controller?

Will there be taints I need to remove when deployed using lokoctl?

**Comment by invidian** [comment]
I think deploying without `worker_` fields should produce you a single controller node cluster. Once deployed, you may want to remove the taint from this node to let regular workloads be scheduled on it.
