### ISSUE TITLE
Kubelet fails to start when enabling --cpu-manager-policy=static

### ISSUE THREAD

**Issue by sneako** [kinvolk/lokomotive#1578]
## Description

I am running a Kubernetes v1.21.4 cluster with FlatCar 2605.9.0 on Equinix Metal c3.medium instances, and trying to enable a static cpu manager policy. After updating the kubelet daemonset manifest to include `--cpu-manager-policy=static` as a kubelet argument, the kubelet gets stuck in a boot loop. Unfortunately I have not been able to retrieve any more logs than the following while the extra arg was provided:

```
Error from server: Get "https://IP:10250/containerLogs/kube-system/kubelet-2sppg/kubelet": EOF


Error from server: Get "https://IP:10250/containerLogs/kube-system/kubelet-2sppg/kubelet": dial tcp IP:10250: connect: connection refused
```

## Impact

I am unable to use a static CpuManagerPolicy in my Kubernetes cluster.

## Environment and steps to reproduce

1. **Set-up**:
- Flatcar version 2605.9.0
- Kubernetes version v1.21.4
- Equinix Metal - DC13 - c3.medium.x86

2. **Task**:
Add `--cpu-manager-policy=static` as an additional kubelet argument

3. **Action(s)**: [ sequence of actions that triggered the bug, see example below ]
Apply the edited manifest

4. **Error**: [describe the error that was triggered]
The kubelet reboots repeatedly until the manifest change is rolled back.

## Expected behavior

The kubelet starts up with a static CpuManagerPolicy.

**Comment by invidian** [comment]
We disscuss it in https://kubernetes.slack.com/archives/C010B5JFB4L/p1641291056004900, it might be because of adding `--cpu-manager-policy` by hand, without specifying the reserved resources, which is required by kubelet.

**Comment by sneako** [comment]
Apologies, this failure appears to be due to the fact that I failed to also configure --kube-reserved and --system-reserved. I will try again using those additional settings and open a new issue if it continues to fail. Thanks for your guidance @invidian !
