### ISSUE TITLE
Decide on enabling persistent storage by default for Grafana

### ISSUE THREAD

**Issue by invidian** [kinvolk/lokomotive#16]
While we should promote immutable approach, with fully automated dashboards (via ConfigMaps etc.), it might be annoying for the users, which create their dashboards by hand to lose them, when Grafana Pod is being removed.

We should consider enabling persistence for Grafana by default and document our recommendation:
- that we don't enable it, so users must be careful. Perhaps some reference to the guide of how to create automated dashboards will be then useful
- that we enable it for convenience, but we highly encourage users to disable it. Again we should point to the guide of how to automate them

**Comment by iaguis** [comment]
We have a how to guide that explains how to create dashboards with configmaps: https://kinvolk.io/docs/lokomotive/0.8/how-to-guides/monitoring-with-prometheus-operator/#add-custom-grafana-dashboards. Closing.
