### ISSUE TITLE
Add ability to upgrade etcd version

### ISSUE THREAD

**Issue by invidian** [kinvolk/lokomotive#161]
Currently we have no way of upgrading etcd version we run cluster on.  Our idea was to replace controller nodes for etcd upgrade, to spawn them with new Ignition configuration using different image tag.

Things to consider:
- single-controller setup upgrades
- preventing incompatible downgrades?
- rollbacks on upgrade failures?

**Comment by invidian** [comment]
For the time being we have a guide how to upgrade it manually: https://github.com/kinvolk/lokomotive/blob/master/docs/how-to-guides/upgrade-etcd.md.

**Comment by iaguis** [comment]
We've been shipping scripts to update etcd.
