### ISSUE TITLE
Re-evaluate which checks we want by default on the linter

### ISSUE THREAD

**Issue by rata** [kinvolk/lokomotive#166]
The linter, while very useful, is creating noise sometimes and I think it is worth to consider what checks we enable by default. We are not using the defaults checks enabled by the linter, but **all**.

This is enforced by the CI, so it can block PRs because of this. And, of course, our code base has tons of errors when running the linter on it. This is working now by just [running the linter](https://github.com/kinvolk/lokomotive/blob/dc1cd16efd939fc77246eef02dfad3c804746aed/Makefile#L62) on the *diff* of the PR (i.e. on line changes done in the PR, instead of the whole file). See the `--new-from-rev` param there.

In my experience, I had been doing things that don't improve the code, but just make the linter happy. This is, of course, failing the goal: the linter shouldn't avoid writing good code or cause too much time to rewrite for no good reason. The linter should just improve code or catch obvious (like things that can be automatic) things.

For now, some comments to disable the linter are being added. It will be nice to revisit which checks we want to enable by default and which we don't (as they cause more trouble than they solve, or would make the code filled with `//nolint` all around the place).

For example, the magic number detection is a check that I've seen issues personally when writing (good, without magic numbers) code. For now, I added this horrible comment as suggested (https://github.com/kinvolk/lokomotive/pull/119#issuecomment-598591236).

I think we should:
 * Decide if we want the linter working how it is now
 * Decide if we want to disable some checks (maybe with experience we will see which ones are the more noisy)
 * Decide if we care about the linter to fix all the warnings in our code base

**Comment by invidian** [comment]
Regarding `gomnd` specifically, I agree that it's a bit annoying, but I think it serves the good purpose, as it always raise a flag when some number is used. For obvious cases, it's perfectly fine to use `//nolint:gomnd` in my opinion. The rationale of using it will be validated on PR review anyway.

About the linter in general, I think the main purpose of it is to make style more opinionated in many cases, which reduces the amount of disagreements and just makes code easier to read, as its consistent everywhere, so in general, the more rules, the better, so long they make sense of course.

**Comment by invidian** [comment]
Is there some annoying linter right now, which we would like to disable? It seems to me, that with recent updates to golangci-lint, they made it pretty good and it's not annoying anymore.

**Comment by rata** [comment]
I haven't checked the new version nor I'm sure if I will have time in the near future. Seems fine to close this for now, if anyone else didn't find issues, and if needed re-open.

These kind of things will pop up if we hit them again, so it is safe to close the bug now, IMHO :)

**Comment by rata** [comment]
Thanks for the ping :)
