### ISSUE TITLE
Conformance tests are failing on 1.17

### ISSUE THREAD

**Issue by invidian** [kinvolk/lokomotive#168]
@invidian commented on [Thu Jan 09 2020](https://github.com/kinvolk/lokomotive-kubernetes/issues/124)

It seem that conformance tests are failing, even with aggregation enabled.
```
Plugin: e2e
Status: failed
Total: 4814
Passed: 278
Failed: 2
Skipped: 4534

Failed tests:
[sig-network] Services should be able to create a functioning NodePort service [Conformance]
[sig-network] Services should be able to change the type from ExternalName to NodePort [Conformance]

Plugin: systemd-logs
Status: passed
Total: 3
Passed: 3
Failed: 0
Skipped: 0
```

```
Sonobuoy Version: v0.17.1
MinimumKubeVersion: 1.15.0
MaximumKubeVersion: 1.17.99
GitSHA: efb9d68ffe37b4eb8e5465252696a7ad523a5ef4
API Version:  v1.17.0
```

Tested on 6f1576fb0db87231877e1236370a42c1bb047fa1 on AWS.

Configuration:
```
module "aws-test-mateusz" {
  source = "../lokomotive-kubernetes/aws/flatcar-linux/kubernetes"

  providers = {
    aws      = "aws.default"
    local    = "local.default"
    null     = "null.default"
    template = "template.default"
    tls      = "tls.default"
  }

  cluster_name = "test-mateusz"
  dns_zone     = "<removed>"
  dns_zone_id  = "<removed>"

  ssh_keys  = ["<removed>"]
  asset_dir = "../cluster-assets"

  controller_count = "1"
  controller_type  = "t3.small"

  worker_count = "2"
  worker_type  = "t3.small"
  networking = "calico"
  network_mtu = ""
  enable_reporting = "false"

  os_image = "flatcar-stable"

  controller_clc_snippets = []
  worker_clc_snippets     = []

  enable_aggregation = "true"
}
```

---

@invidian commented on [Thu Jan 09 2020](https://github.com/kinvolk/lokomotive-kubernetes/issues/124#issuecomment-572618091)

They pass on Packet:
```
Plugin: e2e
Status: passed
Total: 4814
Passed: 280
Failed: 0
Skipped: 4534

Plugin: systemd-logs
Status: passed
Total: 3
Passed: 3
Failed: 0
Skipped: 0Plugin: e2e
Status: passed
Total: 4814
Passed: 280
Failed: 0
Skipped: 4534

Plugin: systemd-logs
Status: passed
Total: 3
Passed: 3
Failed: 0
Skipped: 0
```

```
module "packet-mateusztest" {
  source = "../lokomotive-kubernetes/packet/flatcar-linux/kubernetes"

  providers = {
    aws      = aws.default
    local    = local.default
    null     = null.default
    template = template.default
    tls      = tls.default
    packet   = packet.default
  }

  dns_zone    = "<removed>"
  dns_zone_id = "<removed>"

  ssh_keys  = ["<removed>"]
  asset_dir = "../cluster-assets"

  cluster_name = "mateusztest"
  project_id   = "<removed>"
  facility     = "ams1"

  controller_count = "1"
  management_cidrs = ["<removed>"]
  node_private_cidr = "10.0.0.0/8"

  enable_aggregation = true
}


module "worker-pool-0" {
  source = "../lokomotive-kubernetes/packet/flatcar-linux/kubernetes/workers"

  providers = {
    local    = local.default
    template = template.default
    tls      = tls.default
    packet   = packet.default
  }

  ssh_keys  = ["<removed>"]

  cluster_name = "mateusztest"
  project_id   = "<removed>"
  facility     = "ams1"

  pool_name    = "pool-1"
  worker_count = "2"
  type      = "c2.medium.x86"

  kubeconfig = module.packet-mateusztest.kubeconfig
}
```

---

@mauriciovasquezbernal commented on [Fri Jan 10 2020](https://github.com/kinvolk/lokomotive-kubernetes/issues/124#issuecomment-572796475)

In the AWS configuration you used `enable_aggregation = "true"` while in packet `enable_aggregation = true`, could the quotes have some effect?

---

@invidian commented on [Fri Jan 10 2020](https://github.com/kinvolk/lokomotive-kubernetes/issues/124#issuecomment-572807845)

I don't think so, this is because on AWS I was testing with Terraform 0.11 and on Packet already with Terraform 0.12.

---

@invidian commented on [Tue Jan 14 2020](https://github.com/kinvolk/lokomotive-kubernetes/issues/124#issuecomment-574158046)

The PR with aggregation is now merged, meaning that conformance tests should pass on 1.17 with default configuration on Packet.

For AWS, that still requires investigation.

**Comment by surajssd** [comment]
If you apply following security setting in the `security.tf` OR `assets/lokomotive-kubernetes/aws/flatcar-linux/kubernetes/security.tf` and then install cluster and then run the tests they will pass on AWS.

```tf
resource "aws_security_group_rule" "worker-nodeport" {
  security_group_id = aws_security_group.worker.id

  type      = "ingress"
  protocol  = "tcp"
  from_port = 30000
  to_port   = 32767
  self      = true
}
```


Tests pass with above snippet:

```console
$  sonobuoy status --show-all
         PLUGIN             NODE     STATUS   RESULT
            e2e           global   complete   passed
   systemd-logs    ip-10-0-12-10   complete   passed
   systemd-logs   ip-10-0-26-169   complete   passed
   systemd-logs   ip-10-0-42-222   complete   passed
   systemd-logs     ip-10-0-7-70   complete   passed

Sonobuoy has completed. Use `sonobuoy retrieve` to get results.
```

**Comment by surajssd** [comment]
What are the next steps on this? It was only to fix the issues that were causing the tests to fail right?

**Comment by iaguis** [comment]
Yes, I think we can close this and we can then document running conformance tests in https://github.com/kinvolk/lokomotive/issues/89 and then work on getting certified (we need to create an issue for that).

**Comment by invidian** [comment]
@surajssd does test currently pass on Packet?

**Comment by surajssd** [comment]
Yes they always passed on Packet cloud. I mistakenly ran sonobuoy on Packet first then realised it had to be tested on AWS because that’s where issue was seen as mentioned in description.
