### ISSUE TITLE
Nginx Ingress Controller as an alternative to Contour

### ISSUE THREAD

**Issue by ipochi** [kinvolk/lokomotive#175]
Currently [Ingress component category](https://github.com/kinvolk/lokomotive/blob/master/docs/concepts/components.md#load-balancingingress-for-packet-platform-only) in Lokomotive has only one implementation of Contour. It would be nice to have an alternative component such as Nginx Ingress controller.

**Comment by surajssd** [comment]
Are there any specific issues you see with contour that will be addressed by nginx?

**Comment by invidian** [comment]
>Are there any specific issues you see with contour that will be addressed by nginx?

e.g. propagation of Load Balancer IP address to Ingress object, which is not working in Contour (https://github.com/projectcontour/contour/issues/403)

**Comment by surajssd** [comment]
If that’s the case and if we move ahead with shipping and supporting two ingress providers then we also need to figure out how do we switch ingress class annotation seamlessly in the ingress configuration we ship without having the user to specify that.

**Comment by ipochi** [comment]
@invidian @surajssd 

Now that one of the limitation in Contour was fixed upstream. and since we haven't really decided(mostly don't want to) of supporting alternate components per category. I am of the opinion we close this.

**Comment by surajssd** [comment]
Lets open it when we need it.

**Comment by invidian** [comment]
Closing then.
