### ISSUE TITLE
Write unit tests for lokoctl

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#187]
Up to now we've generated a significant amount of code for lokoctl. A lot of our codebase isn't currently covered by tests. In order to keep the codebase maintainable and allow worry-free refactoring, we need to have reliable unit tests.

We should cover as much of the existing code as possible with unit tests and make it a habit to maintain tests when working on the codebase. Having a good set of tests for the existing code will help people write tests when adding new features.

We may have to refactor some areas of the code to make things testable - things like accepting interfaces instead of concrete types, breaking down big functions to smaller ones etc. This kind of refactoring usually improves the quality of the code as a "side effect", so it may be worth doing anyway.

The tests should eventually be incorporated into the relevant CI pipeline(s) and executed when PRs are opened and after merges.

**Comment by invidian** [comment]
I think we got into habit of adding unit tests for our work, so I think we can close this issue.
