### ISSUE TITLE
Use templatefile function when possible rather than template_file resource

### ISSUE THREAD

**Issue by invidian** [kinvolk/lokomotive#196]
Prior to Terraform 0.12, `template_file` resource was used to do templating in Terraform. With 0.12, now `templatefile` function should be used instead.

**Comment by invidian** [comment]
More context:
>    This commit changes the template method we use in Packet Terraform files
    where possible, from template_file data source coming from 3rd party
    Terraform provider to built-in 'templatefile' function, which is
    available from Terraform 0.12, as it provides the exact same
    functionality, but do not require downloading 3rd party provider.
    Also 'template' provider recommends using this function:
    https://www.terraform.io/docs/providers/template/d/file.html.

**Comment by invidian** [comment]
Just found out some pros and cons about it:
- Good thing about `templatefile()` is that it allows you to pass complex type to the template, like lists, so you can iterate inside the template
- If you want to calculate the result of `templatefile()` with use of `count`, you need to use some helper, e.g. `null_resource`, where with `template_file` you can use the `count` directly.

IMO `templatefile()` seems still better, as we use `null` provider anyway for other things and we could completely get rid of `template` provider. This would mean less download for the end user.

**Comment by invidian** [comment]
Turns out `template` provider is now deprecated: https://github.com/hashicorp/terraform-provider-template.

**Comment by knrt10** [comment]
On it
