### ISSUE TITLE
Packet: specify hardware reservations and dependencies between worker pools

### ISSUE THREAD

**Issue by rata** [kinvolk/lokomotive#20]
It should be possible to specify hardware reservations in Packet (supported in terraform code).

However, there is an issue in packet terraform provider in which we need to create some worker pools before another when using hardware reservations "next-available" and a specific UUID. Upstream bug was reported [here](https://github.com/terraform-providers/terraform-provider-packet/issues/176) and the "fix" was to document to create such dependencies manually. 

Without that (workaround in terraform is just doing `terraform apply -target ...`) is not possible to reliably create clusters that mix "next-available" and specific UUIDs.

Such clusters are useful because you may want to run with reserved instances only (for pricing reasons) but you need to spread some workers in specific ways and need to specify UUIDs too.

**Comment by rata** [comment]
A work in progress (with some fixes for things I found in the way) is here: https://github.com/kinvolk/lokomotive/tree/rata/packet-improve-reservations

**Comment by surajssd** [comment]
@rata could you create a PR (even a draft one will work) so that it is easy to review and see what is going on?

**Comment by rata** [comment]
Sure, not ready for review, but will create the draft PR :)

**Comment by rata** [comment]
Done: https://github.com/kinvolk/lokomotive/pull/119 :)

**Comment by rata** [comment]
Moved to 0.2.0 as 0.1.1 is probably not going to be released
