### ISSUE TITLE
Add cred path variable similar to packet platform

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#220]
There is a variable in [Packet configuration](https://github.com/kinvolk/lokomotive/blob/master/docs/configuration-reference/platforms/packet.md#attribute-reference) called `aws_creds_path` which allows me to specify the path to the credetials file. But [AWS platform](https://github.com/kinvolk/lokomotive/blob/master/docs/configuration-reference/platforms/aws.md) there is no way to do it.

Please add `cred_pah` var to AWS as well.

**Comment by surajssd** [comment]
Another alternative is using `AWS_CONFIG_FILE` which does not work with lokoctl as it is a standard env var that can be used with aws sdk https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

**Comment by johananl** [comment]
We don't need any vars or knobs for handling AWS credentials. All of this is already handled for us by the AWS SDK and any logic we add is just duplication.

For this specific case, setting the `AWS_SHARED_CREDENTIALS_FILE` env var has the desired effect.

**Comment by johananl** [comment]
Also, that knob has been removed from the Packet platform in #422.
