### ISSUE TITLE
container image for kubelets

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#221]
Kubelet is still provisioned using hyperkube container image. Upstream will stop shipping any image for kubelet (will only ship binaries for it).

* Upstream issue for ref: https://github.com/kubernetes/kubernetes/pull/88676
* Deprecation mentioned in v1.17.x change log: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#cluster-lifecycle-1

---

So going forward we either need to build and maintain images for kubelet.
OR
We can use the images that are built for typhoon: `quay.io/poseidon/kubelet:v1.18.0`.

**Comment by invidian** [comment]
Upstream reference?

**Comment by surajssd** [comment]
@invidian done. Thanks for catching that.

**Comment by invidian** [comment]
What I've done for https://github.com/flexkube is that I forked https://github.com/poseidon/kubelet and pushed my own build to quay.io. Perhaps we should do the same?

**Comment by surajssd** [comment]
Apart from ownership what is the advantage of using our image?

**Comment by invidian** [comment]
We can update/patch on our own, instead of relying on others to do that. Also, this way we potentially limit the hit if some malicious images are published to poseidon.

**Comment by iaguis** [comment]
We maintain our own images now.

**Comment by ipochi** [comment]
1. Cloned https://github.com/poseidon/kubelet  to https://github.com/kinvolk/kubelet
2. Created a new default branch `kinvolk-master`
3. Created a PR for Kubelet 1.21.4 against `kinvolk-master`  branch and published the images to `quay.io/kinvolk/kubelet`

Step 3 to be repeated in case of an update of Kubelet.
