### ISSUE TITLE
Update terraform-provider-ct version

### ISSUE THREAD

**Issue by iaguis** [kinvolk/lokomotive#223]
[v0.5.0 was released](https://github.com/poseidon/terraform-provider-ct/releases/tag/v0.5.0), we should update it.

In the docs we say terraform-provider-ct should be installed but we don't mention any version, we should consider mentioning it to avoid user problems when a new version is released and we haven't updated yet.

Reported-by: @jpetazzo

**Comment by invidian** [comment]
While on it, maybe we could work on shipping the provider built-in, so it will be automatically updated for the user?

**Comment by iaguis** [comment]
Let's fix this documenting and updating to the latest version and we can later try to 1) get the provider to terraform upstream and/or 2) consider shipping it built-in
