### ISSUE TITLE
Simplify sample configs in quickstart guides

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#244]
I find the way we handle config params in sample configs confusing:

- For some params, we "wrap" the value in another `variable` directive within the config file ([example](https://github.com/kinvolk/lokomotive/blob/49e8346d89408856bd54bbe86cc4b2353b0ee81a/examples/aws-production/cluster.lokocfg#L8-L10)). I suggest we simply put the value directly under the `cluster` block because it's more readable and easier to follow. I don't see a good reason to use an HCL `variable` clause here.
- We [ask](https://github.com/kinvolk/lokomotive/blob/b42eae169575204dd762ec2709668ba3ed826756/docs/quickstarts/packet.md#step-4-define-cluster-configuration) the user to provide *some* parameters via `lokocfg.vars`, but not others. I think we want to have all config knobs in one place in our quickstart examples, unless there is a very good reason not to do so. Simplicity should be paramount in quickstart guides.
- We use "placeholder text" in many of the variables. Instead of writing `management_cidrs = "public-ip-address-cidr-to-access-the-cluster"`, I suggest we write `management_cidrs = "1.2.3.4/32"`. The whole idea of an example is that it **demonstrates** something rather than **explain** it. If we want to explain what this knob *does*, we can do so below the snippet and/or in our config **reference**.

**Comment by iaguis** [comment]
This has improved, I think we can close.
