### ISSUE TITLE
Explain MetalLB address pool in Packet quickstart

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#247]
In the Packet quickstart guide we [refer](https://github.com/kinvolk/lokomotive/blob/b42eae169575204dd762ec2709668ba3ed826756/docs/quickstarts/packet.md#step-4-define-cluster-configuration) the user to a sample config which contains the variable `metallb_address_pool`. This variable isn't mentioned in the guide although it is required for the deployment to work if MetalLB is deployed. We should:

- [ ] Explain what value the user needs to provide here.
- [ ] List at least one EIP as a requirement.

**Comment by iaguis** [comment]
Metallb won't be deployed as a part of the quickstart after https://github.com/kinvolk/lokomotive/pull/332. Closing.
