### ISSUE TITLE
Update prometheus operator

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#257]
Right now we cannot do it right away because:

> Even though we set the `name` in `metadata` in `volumeClaimTemplates` (https://github.com/coreos/prometheus-operator/issues/2865) but they are not respected by the operator and we still get PVC with long names.
> 
> This one is blocked on https://github.com/coreos/prometheus-operator/issues/3093.

Once above issues are fixed then create a PR to update.

**Comment by invidian** [comment]
Done now :ok_hand:
