### ISSUE TITLE
Allow to configure dex/gangway let's encrypt cluster issuer

### ISSUE THREAD

**Issue by rata** [kinvolk/lokomotive#260]
Today, dex&gangway configuration mention a Let's Encrtypt Issuer in their configuration and they assume they have a specific name.

That works fine when the cert-manager is deployed via lokoctl, but can fail with custom cert-manager deployments, as the custom deployment may use a different name for the Let's Encrypt cluster Issuer.

**Comment by invidian** [comment]
Implemented in #482.
