### ISSUE TITLE
contour: Add note explaining why service uses externalTrafficPolicy: Local

### ISSUE THREAD

**Issue by rata** [kinvolk/lokomotive#263]
This commit 641704fc5a2878e5fd1b963af84710cae2bd489f removed the `XXX` comment saying to not remove that line.

While the line is still there, we should document (in the yaml/go code where [it is now](https://github.com/kinvolk/lokomotive/blob/4589317d7af58c951cf5369782d6263c685623ad/pkg/components/contour/template.go#L36) or in some other place) why that is needed.

btw, that is needed for sourceIP preservation. But a long fat comment explaining in more detail is what this issue is about.

**Comment by surajssd** [comment]
@rata it was removed because it is same as upstream now https://github.com/projectcontour/contour/blob/9dced6846f026cf7bc45f64b29799ec4b9d8b41c/examples/contour/02-service-envoy.yaml#L16

We are not doing any custom changes there.

**Comment by rata** [comment]
@surajssd Oh, awesome! Thanks!
