### ISSUE TITLE
Add blackbox test to do port scanning on all nodes of the cluster

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#272]
- This test should scan all the ports and fail on any open port found except for the whitelisted ones.
- Add instructions on [release doc](https://github.com/kinvolk/lokomotive/blob/master/docs/RELEASING.md) on how to run this test.

cc: @johananl please edit if I missed something here.

**Comment by invidian** [comment]
Duplicate of #190

**Comment by surajssd** [comment]
Ah my bad!
