### ISSUE TITLE
Fix phrasing and hyperlink in Packet quickstart

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#274]
https://github.com/kinvolk/lokomotive/blame/5e4f3c2884c1d018e29186d5aee68d4b51d1f653/docs/quickstarts/packet.md#L73-L74

>Lokomotive requires AWS credentials for configuring Route53 DNS. To manually configure DNS entries refer the DNS configuration settings for Packet(Add link).

- Change "Route53 DNS" to "DNS on Route 53".
- Add missing "to" after "refer".
- Add a missing space after "Packet".
- Change "Add link" with an actual link.

**Comment by BrainBlasted** [comment]
The packet quickstart has undergone major changes since this issue was open, and the relevant lines are no longer there. Is there any other phrasing in the quickstart that needs changing?

**Comment by johananl** [comment]
No, thanks @BrainBlasted. This is all fixed AFAICT.
