### ISSUE TITLE
Remove redundant calico hostendpoint controller configs

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#285]
Configs of component exist in two places: 1) https://github.com/kinvolk/lokomotive/tree/master/assets/lokomotive-kubernetes/packet/flatcar-linux/kubernetes/calico-host-protection
and 2) https://github.com/kinvolk/lokomotive/tree/master/assets/components/calico-hostendpoint-controller/manifests.

We should get rid of one. Right now the configs that are installed by default are from 1st.

**Comment by invidian** [comment]
This seems like a leftover after merging the repositories.
