### ISSUE TITLE
Fix calico-related bootkube errors

### ISSUE THREAD

**Issue by iaguis** [kinvolk/lokomotive#3]
When booting a cluster, the following error is shown in the bootkube logs:

```
Sep 11 12:54:02 kinvolk-dev-test-controller-0 bootkube-start[1952]: [ 1532.151750] bootkube[6]: Failed creating /assets/manifests/calico-policy.yaml  : dicovery failed: discover group verison : groupVersion shouldn't be empty
```

This doesn't seem to cause any harm but it should not happen.

**Comment by knrt10** [comment]
I don't think this still persists. Verified it at the latest release as seen on below image. So closing it

![bootkube preview](https://user-images.githubusercontent.com/24803604/91143948-eeab2100-e6d0-11ea-8973-f5cb6827a908.png)
