### ISSUE TITLE
Encrypt inter pod traffic 

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#304]
This is needed since applications talking among themselves don't employ SSL when traffic is local to a single k8s cluster. But someone who has access to a node can snoop on traffic.

## Proposed solution

I recommend that lokoctl ship **istio** as a default component. Istio enables encrypted inter pod traffic by default. This also allows us to provide policies similar to networkpolicy to control traffic flow. And istio also provides mTLS as an added benefit.

Above solution can be discussed for other alternative that provide all the features mentioned above.

## Demo

Following pods are running in the cluster:

```console
$ kgp -o wide
NAME                   READY   STATUS    RESTARTS   AGE   IP            NODE                               NOMINATED NODE   READINESS GATES
fedora                 1/1     Running   0          13m   10.2.153.10   suraj-lk-cluster-pool-1-worker-0   <none>           <none>
web-5dcb957ccc-cnrld   1/1     Running   0          26m   10.2.76.12    suraj-lk-cluster-pool-1-worker-2   <none>           <none>
```

On `suraj-lk-cluster-pool-1-worker-2` where `web` OR `nginx` pod is running, if I snoop traffic there I can read what is being sent:

```console
$ sudo tcpdump -i any -A -s 0 'tcp port 80 and (((ip[2:2] - ((ip[0]&0xf)<<2)) - ((tcp[12]&0xf0)>>2)) != 0)'
...
08:03:56.964692 IP 10.2.76.12.http > 10.2.153.10.56208: Flags [P.], seq 240:852, ack 74, win 224, options [nop,nop,TS val 1564549297 ecr 127887487], length 61
2: HTTP
E.....@.?..I
.L.
..
.P...~.El.D............
]A ...h.<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

^C
```

Above results can also be obtained on `suraj-lk-cluster-pool-1-worker-0` where the client (in this case `curl` on `fedora` pod) is running.

**Comment by invidian** [comment]
This is a duplicate of #10.
