### ISSUE TITLE
Block access to metadata URL of Packet from within the pods

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#305]
We have metadata URL that can be used to get more information about nodes. Which is not needed for someone running workloads on the node. So block access to the URL from within the pods: https://metadata.packet.net/metadata .

**Comment by invidian** [comment]
As discussed on Slack, maybe we could block by default all connections outside of the cluster?

**Comment by pothos** [comment]
Of higher interest would be https://metadata.packet.net/userdata which is more likely to contain secrets. I think it's worth to distinguish between outgoing Internet connections and connections to the metadata server (`192.80.8.124` or even the whole subnet) because if a workload is granted Internet access I wouldn't grant it access to the internal metadata server.

**Comment by rata** [comment]
Some workloads do need it, though. The VPN component is an example of that, so we would need to allow it conditionally or modify the VPN to not use that (I think the latter might be possible by using the flatcar metadata, if we improve it to include other info needed, but is a wider effort, of course).

And, of course, this applies to other platforms (like AWS), should we create an issue for that? Or a general umbrella issue? (I think both can be kind/roadmap, but not sure)

**Comment by invidian** [comment]
>And, of course, this applies to other platforms (like AWS), should we create an issue for that? Or a general umbrella issue? (I think both can be kind/roadmap, but not sure)

I think umbrella issue could be providing some default NetworkPolicies on all platforms.

>Some workloads do need it, though. The VPN component is an example of that, so we would need to allow it conditionally or modify the VPN to not use that (I think the latter might be possible by using the flatcar metadata, if we improve it to include other info needed, but is a wider effort, of course).

In this case, I think the VPN component should bring their own NetworkPolicy to ensure it has access to it. It should work on top of default policies of course.

**Comment by rata** [comment]
> > And, of course, this applies to other platforms (like AWS), should we create an issue for that? Or a general umbrella issue? (I think both can be kind/roadmap, but not sure)
> 
> I think umbrella issue could be providing some default NetworkPolicies on all platforms.

Sounds good to me!



> In this case, I think the VPN component should bring their own NetworkPolicy to ensure it has access to it. It should work on top of default policies of course.

Ohh, right! For some reason I was not thinking in NetworkPolicy object (and something like `iptables -d <metadata_ip> -j DROP`). If it allows that expressiveness, it makes way more sense! :)

**Comment by invidian** [comment]
Metadata docs of Packet: https://www.packet.com/developers/docs/servers/key-features/metadata/.
