### ISSUE TITLE
Automated certificate renewal

### ISSUE THREAD

**Issue by iaguis** [kinvolk/lokomotive#309]
We should have a way to rotate certificates automatically. For this we'll probably need:

- [x] [Enable TLS bootstrapping for nodes](https://github.com/kinvolk/lokomotive/issues/177)

**Comment by surajssd** [comment]
Updated the description since it pointed to the same issue.

**Comment by iaguis** [comment]
After https://github.com/kinvolk/lokomotive/pull/1435 we have automated cert rotation.
