### ISSUE TITLE
Submit conformance test results and get certified

### ISSUE THREAD

**Issue by iaguis** [kinvolk/lokomotive#310]
We have a [documented way of running conformance tests](https://github.com/kinvolk/lokomotive/blob/841a35fa9473a361eff00ec4a27f85422dfddc89/docs/run-conformance-tests.md). We should run them and send them to get certified.

**Comment by iaguis** [comment]
This is done for v0.1.0: https://github.com/cncf/k8s-conformance/pull/959

**Comment by invidian** [comment]
@iaguis should we add a certified badge into the readme?

**Comment by iaguis** [comment]
Sounds good! https://github.com/kinvolk/lokomotive/pull/418
