### ISSUE TITLE
Remove CoreOS support from Terraform code

### ISSUE THREAD

**Issue by invidian** [kinvolk/lokomotive#324]
For example, Terraform code for bare-metal provider still supports CoreOS, we should remove it.

**Comment by invidian** [comment]
Done for bare-metal in #1246. For AWS there is a PR #1245.

**Comment by kskewes** [comment]
After those, the last one remaining is Azure I believe.

I had a look and it seems that it doesn't use `os_channel` or `os_version` variables like the others. It expects a [`var.custom_image_name`](https://github.com/kinvolk/lokomotive/blob/master/assets/terraform-modules/azure/flatcar-linux/kubernetes/controllers.tf#L35) to be supplied.

I haven't used Azure before and not sure how the `data "azurerm_image"` works (compared with AWS/GCP/etc). I wasn't able to find an image lookup website to learn how we can supply our usual flatcar, channel and version variables - if such a mechanism (not only Packer) exists.

**Comment by invidian** [comment]
I think we can ignore Azure for now, as it is not exposed in `lokoctl`. We will have to fix bunch of stuff there anyway when we decide to expose it.

**Comment by invidian** [comment]
Finished in #1245
