### ISSUE TITLE
AWS: ingress not working by default

### ISSUE THREAD

**Issue by schu** [kinvolk/lokomotive#349]
Worker pool and NLB target group configuration doesn't match in a default Lokomotive setup on AWS and ingress doesn't work out of the box.

There are two problems:

* The NLB target groups for port 80 and 443 are empty after installation. (`<clustername>-workers-http`/`<clustername>-workers-https`). The worker pool target groups (`<poolname>-workers-http`/`<poolname>-workers-https`) on the other hand are not configured with the NLB.

* The NLB target group's health check is configured to check target nodes for health on port `:10254/healthz`, but that port is not actually used / listend on anymore.

Manually adding the worker nodes to the NLB target groups and changing the health check configuration to theck port `80`/`443` (the target ports) instead is a workaround.

**Comment by johananl** [comment]
Fixed in https://github.com/kinvolk/lokomotive/pull/367.
