### ISSUE TITLE
Ability to add different set of ssh keys for controller and worker pools in AWS and Packet

### ISSUE THREAD

**Issue by ipochi** [kinvolk/lokomotive#356]
Ideally user should be able to configure the Lokomotive cluster with the ability to have different set of ssh keys for controller nodes and worker pool nodes.

Currently same set of ssh_keys is used for all nodes.

**Comment by ipochi** [comment]
For AWS - this requires changes at `assets/lokomotive-kubernetes` level.
For Packet - #355 adds the ssh keys field in worker pool configuration.

**Comment by invidian** [comment]
Also related #578.

**Comment by johananl** [comment]
Closing in favor of #578.
