### ISSUE TITLE
AWS: Make SSH public keys DRY

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#358]
Currently we ask the user to provide a list of SSH public keys for both the controllers and the workers. Since it is likely that in most situations users would want to use the same key for both machine types, we should ask for one value and use it for both controllers and workers.

For the sake of flexibility, we could allow a per-worker-pool value while using the "global" set of keys by default.

**Comment by ipochi** [comment]
@johananl For AWS, the ability to have a different set of ssh_keys for AWS needs changes  in the terraform code in `assets/lokomotive-kubernetes`

The user can still provide one value and use it in both places.

```
variable ssh_keys {}

cluster {
  ...
  ssh_keys = var.ssh_keys
  worker_pool "p1" {
  ... 
  ssh_keys = var.ssh_keys
  }
}
```

**Comment by johananl** [comment]
>For AWS, the ability to have a different set of ssh_keys for AWS needs changes in the terraform code in assets/lokomotive-kubernetes

Right. Are you saying this is a problem?

**Comment by surajssd** [comment]
Providing same set of keys for the workers and controllers is what most users would want as well. So by default that should be our behaviour. Keys provided once should be used in other places. Right now this place could be most likely the `controller` section of the `cluster`.

**Comment by johananl** [comment]
We don't have a `controller` section under `cluster` though... But yes, your idea is what I had in mind: take a "global" set of keys and allow per-worker-pool overrides.

**Comment by invidian** [comment]
Seems similar to #578 and #356

**Comment by surajssd** [comment]
So do we close this in favour of the others?

**Comment by invidian** [comment]
I'm not sure, all 3 issues seems similar to me and I cannot distill the specific difference between them from the top of my head :smile:

**Comment by johananl** [comment]
They all touch the same issue but are phrased differently AFAICT. Let's close this one (#358), rephrase the title of #578 to be clearer and add the content of #356 to #578 (applying the solution to both AWS and Packet).
