### ISSUE TITLE
Consider testing HA setup on the CI

### ISSUE THREAD

**Issue by invidian** [kinvolk/lokomotive#363]
To avoid bugs like #347.

This of course means, bigger costs and bigger testing matrix.

**Comment by rata** [comment]
I don't see why not, if we plan to support this and is very relevant to most production deployments.

If the testing matrix is a problem, I'd remove the 1 controller test in favor of the HA controller, even.

**Comment by surajssd** [comment]
Can we just convert the existing CI pipeline for AWS and Packet to start 2 controllers instead of 1?

This way we test HA control plane by default? And about testing 1 controller control plane it is low priority because our customers won’t be running single controller cluster in production.

**Comment by rata** [comment]
I think we should test both, but if we need to test only one, as I mentioned, we should test HA. For the same reasons @surajssd mentions :)

**Comment by iaguis** [comment]
We now test HA on each PR and single-controller on Flatcar Edge on every push to master. Closing.
