### ISSUE TITLE
Handle AWS ELB target group names > 32 characters

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#366]
ELB target groups are limited to 32 characters on the AWS API. Since we interpolate the cluster name and worker pool name into the target group, long cluster/pool names may exceed this limit.

At the moment there is no check in place for this limit - we fail the deployment with a not-so-nice Terraform error. Ideally we should find a way to never hit this limit. An alternative would be to validate the config and fail fast if necessary.

**Comment by johananl** [comment]
Handled in https://github.com/kinvolk/lokomotive/pull/367. We simply let Terraform generate a random target group name and put the meaningful info (cluster + worker pool name) in AWS tags.

**Comment by invidian** [comment]
See also #282.

**Comment by johananl** [comment]
#367 is merged. Closing.
