### ISSUE TITLE
Document all the AWS permissions needed for Packet deployment

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#373]
We need AWS for Packet cluster deployment. Document all the permissions a user needs when deploying such a cluster. Provide an IAM policy json file.

So the permissions include access to following:

If using S3 to store the state:

- S3 bucket
- DynamoDB table

If using Route53 to create DNS records for control plane:

- Route53

**Comment by iaguis** [comment]
I found the minimal set of permissions required for Route53 is:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "route53:GetChange",
                "route53:GetHostedZone",
                "route53:ChangeResourceRecordSets",
                "route53:ListResourceRecordSets",
                "route53:ListTagsForResource"
            ],
            "Resource": [
                "arn:aws:route53:::change/*",
                "arn:aws:route53:::hostedzone/<HOSTED_ZONE_ID>"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "route53:ListHostedZones",
            "Resource": "*"
        }
    ]
}
```

And the permissions for the S3 backend are detailed here: https://www.terraform.io/docs/backends/types/s3.html

I think we want to refer to this information from the quickstarts and from the platform reference. Should we create a separate document with it?

Tagging @johananl since he's doing a quickstart rework.

**Comment by iaguis** [comment]
> @iaguis IMO this may belong in a "concepts" document for the AWS platform. In any case I would't put IAM policies in the config reference because this isn't config-related info.

Hm, actually this is about the AWS permissions needed for a Packet deployment.

* For DNS, we now have the Cloudflare provider so I think I can include this in `docs/concepts/dns.md`.
* For the S3 storage backend I can include them in `docs/configuration-reference/backend/s3.md`

Does that sound OK?

**Comment by iaguis** [comment]
> Does that sound OK?

Created a PR, we can discuss there.
