### ISSUE TITLE
Add Cloudflare DNS support

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#385]
## General

CloudFlare is a widely-used DNS provider. It would be useful to add support for it as an official provider (rather than just using the `manual` DNS option).

## Implementation

It should be easy to add CloudFlare support using https://www.terraform.io/docs/providers/cloudflare/r/record.html. We already have the necessary abstraction in place and implementation should be nearly identical to Route 53.

**Comment by iaguis** [comment]
Fixed by #422
