### ISSUE TITLE
AWS: Remove default worker pool

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#396]
Currently we create a "default" worker pool on AWS. This pool is created in addition to the pools created according to `worker_pool` blocks and is of size 0. We should remove this pool and let users explicitly control all worker pools.

Fixed in https://github.com/kinvolk/lokomotive/pull/367.

**Comment by invidian** [comment]
AKS cluster cannot be created with no worker pools. There must be at least one, but it's configuration is being pulled from the `worker_pool` block.

**Comment by johananl** [comment]
So how do things work from the UX perspective?

What happens if I:

- Create a `cluster` block without any `worker_pool` blocks?
- Create a `cluster` block with one `worker_pool` block?
- Create a `cluster` block with multiple `worker_pool` blocks?

I want to verify the UX is similar across platforms.

**Comment by invidian** [comment]
>Create a cluster block without any worker_pool blocks?

Validation of such configuration will fail:
- https://github.com/kinvolk/lokomotive/blob/8e0529a0b5264e12a66bbd24a0f149a719473c97/pkg/platform/aks/aks_test.go#L59-L63
- https://github.com/kinvolk/lokomotive/blob/8e0529a0b5264e12a66bbd24a0f149a719473c97/pkg/platform/aks/aks.go#L227-L239

>Create a cluster block with one worker_pool block?

First defined block will be used as a default one.

> Create a cluster block with multiple worker_pool blocks?

Again, first block will be used as a default pool, next blocks will be extra pools.

**Comment by johananl** [comment]
SGTM. Then we just need to fix AWS then, which is already handled. I'll update the issue.

**Comment by johananl** [comment]
#367 is merged. Closing.
