### ISSUE TITLE
Test rook-ceph component in e2e tests

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#397]
Right now we test only rook which essentially does not deploy anything important(it deploys operator which is kicked into action once we create a CR called `CephCluster` using `rook-ceph` component).

So this deploy rook-ceph via CI config. But before doing this we need to make sure there are machines available to run rook-ceph on. This component needs raw disk which it uses for its own purpose, they can't conflict with OpenEBS. So we need to add extra machines, label them so that rook is deployed there and now use some other component to test if it can create PVC from rook.

**Comment by surajssd** [comment]
Add e2e monitoring tests as well while someone is working on this. As mentioned in https://github.com/kinvolk/lokomotive/pull/405#issuecomment-626521195

**Comment by invidian** [comment]
Partially done in https://github.com/kinvolk/lokomotive/pull/1084. Will be finished in #1153.
