### ISSUE TITLE
Set custom labels and taints for AWS platform

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#4]
## Description

In Lokomotive for AWS add support for custom labels and taints for worker nodes. Just like packet has.

- Custom Labels: https://github.com/kinvolk/lokomotive-kubernetes/blob/0da7e1426119a6b1539ff45a2f0adbcc7198842b/packet/flatcar-linux/kubernetes/workers/variables.tf#L37-L43
- Custom Taints: https://github.com/kinvolk/lokomotive-kubernetes/blob/0da7e1426119a6b1539ff45a2f0adbcc7198842b/packet/flatcar-linux/kubernetes/workers/variables.tf#L45-L49

## Initial task breakdown

- [ ] Add the variables like it is done in Packet.
- [ ] Consume them at the Kubelet level flags.
- [ ] Make sure to port those above changes to the Lokoctl.
- [ ] Add test to lokoctl which verify that such labels/taints have been added.
- [ ] Add docs that show how to use this feature.

## Acceptance Criteria

- [ ] User can set labels and taints from lokoctl and create cluster and verify that those have been applied succefully.

## Follow up work

- Create similar issues/work for other supported providers (Azure, Baremetal, Google Cloud, KVM Libvirt)

**Comment by knrt10** [comment]
I can take this up
