### ISSUE TITLE
Understanding output/maintenance

### ISSUE THREAD

**Issue by danielgormly** [kinvolk/lokomotive#400]
Hi,

Great project!

I will try to dig through the code & understand how it all fits together and the general lifecycle - particularly changes after initial boot, but in general I have a question about the vision regarding best practices of maintenance and committing an existing cluster state / asset files into a code repository and which of that is sensitive data.

Assuming I'm using the same version of lokoctl, I'm mostly curious about what generated files I need to keep (i.e. non-deterministic outputs)? I obviously need to keep the CA and most/all TLS certs (cluster-assets/tls), as well as K8s auth config, and the cluster state (in my case via S3 backend).

Or is it much safer to just commit everything in the cluster-assets / lokomotive-kubernetes folders, granted I will have to encrypt some of these.

Thank you (& apologies for the vague question)

**Comment by invidian** [comment]
Hey @danielgormly, thanks for the question. I'm happy to clarify.

If you use [S3](https://github.com/kinvolk/lokomotive/blob/master/docs/configuration-reference/backend/s3.md) backend for your configuration, then assets directory is disposable (assuming that you didn't do any manual changes there) and will be re-generated on next run of `lokoctl cluster apply`. You may want to backup `cluster-assets/auth/kubeconfig` file as well, depending how you access the cluster.

>I obviously need to keep the CA and most/all TLS certs (cluster-assets/tls)

Content of those files is stored in Terraform state, so they will be re-created as well.

**Comment by danielgormly** [comment]
Thanks! That's great to hear.
