### ISSUE TITLE
Document API server modifications required for Dex

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#428]
At the moment the user needs to modify flags on the API server before Dex can be used for authentication:

```
--oidc-issuer-url=https://dex.example.lokomotive-k8s.org
--oidc-client-id=gangway
--oidc-username-claim=email
--oidc-groups-claim=groups
```

https://github.com/kinvolk/lokomotive/issues/380 might remove the need for this manual operation, however until this issue is resolved (or if we decide not to solve it for any reason), we should have the necessary flags documented in the Dex component docs.

**Comment by iaguis** [comment]
we have it in the [Dex+Gangway howto](https://github.com/kinvolk/lokomotive/blob/v0.1.0/docs/how-to-guides/authentication-with-dex-gangway.md#step-5-configure-the-api-server-to-use-dex-as-an-oidc-authenticator) but I guess you're suggesting adding it to the Dex (or Gangway) configuration reference?

**Comment by johananl** [comment]
I wanted it to be documented *somewhere* as @surajssd and myself couldn't find this info today. A how-to guide actually sounds like the right place IMO since these flags aren't part of the component config but are rather "something that the user needs to do". Closing.
