### ISSUE TITLE
Document TLS Handshake errors on AWS single master cluster

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#438]
On apiserver you can see multiple TLS Handshake errors as reported in https://github.com/kinvolk/lokomotive/issues/278.

But this is cannot be fixed on AWS if the cluster has single node master. So document it as mentioned in: 

> For AWS, the TLS handshake errors cannot be resolved, as they are caused
> by AWS Load Balancer, which is configured to only TCP checks and in HTTP
> mode, it does not support authentication header, so we would have to
> remove --anonymous-auth=false kube-apiserver option, which we shouldn't
> do.

https://github.com/kinvolk/lokomotive/issues/278#issuecomment-614574108

cc: @invidian

**Comment by invidian** [comment]
>But this is cannot be fixed on AWS if the cluster has single node master

This is regardless of the number of masters. This is AWS ELB limitation.

Also, upstream issue with proposed fix: kubernetes/kubernetes#91050.

**Comment by invidian** [comment]
Created PR for this #599.

**Comment by invidian** [comment]
BTW, this will be fixed in K8s 1.19: https://github.com/kubernetes/kubernetes/pull/91277.
