### ISSUE TITLE
SIGINT to lokoctl is not handled gracefully

### ISSUE THREAD

**Issue by iaguis** [kinvolk/lokomotive#45]
Right now receiving SIGINT in lokoctl (Ctrl-C) is not handled so if, say, this happens while terraform is running we might end up in a bad state.

We should handle SIGINT and exit gracefully.

**Comment by ipochi** [comment]
Part of this issue in #329 is fixed in #483
Another issue in this umbrella is filed under #555

**Comment by BrainBlasted** [comment]
I know terraform could end up leaving a lock behind if a SIGINT is received, but what else could lead to a "bad state"?

**Comment by iaguis** [comment]
It could also leave processes behind (this is what we fixed in https://github.com/kinvolk/lokomotive/issues/329) and maybe data loss (this is what appears in terraform when you send the first SIGINT: "Please wait for Terraform to exit or data loss may occur.").

The main thing that's missing now is what's described in https://github.com/kinvolk/lokomotive/issues/555, when the user sends SIGINT while terraform init/refresh/plan is running, lokomotive continues with the next steps, but it should stop.

**Comment by iaguis** [comment]
Closing in favor of #555
