### ISSUE TITLE
Document how to access Prometheus, Alertmanager, Grafana

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#450]
We don't have documentation for above.

---

For Grafana:

```
kubectl -n monitoring port-forward svc/prometheus-operator-grafana 8080:80
```

goto http://localhost:8080

For Prometheus:

```
kubectl -n monitoring port-forward svc/prometheus-operator-prometheus 9090:9090
```

goto http://localhost:9090

**Comment by invidian** [comment]
How does this issue relate to #350?

**Comment by surajssd** [comment]
It does not relate to it in anyway. The issue recommends creating ingress, and we don't recommend creating ingress. Since it is not safe to create ingress to expose over internet despite the fact that it has password.

**Comment by surajssd** [comment]
We should document that too. BTW.
