### ISSUE TITLE
Fix MetalLB speaker and controller scheduling

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#46]
At the moment we have two problems with the way we schedule MetalLB pods:

1. Speaker pods are scheduled on both worker nodes and controller nodes.
1. The controller pod is scheduled on a worker node.

We should ensure speaker pods never run on controller nodes because controller nodes don't serve application traffic and therefore don't need to participate in BGP. Currently we set the following toleration for speaker pods:

https://github.com/kinvolk/lokomotive/blob/df30e7ddbfd1058699c9a834b1040f27e33ee6f4/pkg/components/metallb/component.go#L70-L73

We should ensure the controller pod runs on a controller node to avoid unnecessary interruptions to MetalLB due to cluster scaling events.

**Comment by invidian** [comment]
>We should ensure the controller pod runs on a controller node to avoid unnecessary interruptions to MetalLB due to cluster scaling events.

Can't controller run in HA on worker nodes? I think we should avoid putting things in controller nodes in general, unless it affects cluster operation or allows to take over the cluster, if given workload is compromised.

**Comment by johananl** [comment]
I don't know if MetalLB can run with multiple controllers. From a user's perspective, failed BGP definitely affects cluster operation. But I haven't tested the impact of a re-scheduled/evicted controller pod.
