### ISSUE TITLE
Dex and Gangway becomes unusable after `lokoctl cluster apply`

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#460]
So I had a cluster with Dex and Gangway installed. And post installation I also added those flags to the apiserver daemonset.

```yaml
        - --oidc-issuer-url=https://dex.foobar.io
        - --oidc-client-id=gangway
        - --oidc-username-claim=email
        - --oidc-groups-claim=groups
```

But due to some reason I had to delete a node and to reconcile the cluster I ran `lokoctl cluster apply` which rendered the Dex and Gangway unusable because it removed those flags I added manually.

**Comment by iaguis** [comment]
Yes, this is a known issue and it will be when https://github.com/kinvolk/lokomotive/issues/380 is closed (PR is up https://github.com/kinvolk/lokomotive/pull/182)

**Comment by iaguis** [comment]
Closing as duplicate.
