### ISSUE TITLE
Packet: handle automatic authorization of all API-level SSH keys

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#465]
The Packet [API](https://www.packet.com/developers/api/devices/) has two knobs which control which SSH keys are authorized on a device: `project_ssh_keys` and `user_ssh_keys`. Both of these keys accept a list of **IDs** which reference public keys which are known to the Packet API.

Lokomotive doesn't use this mechanism at all, but rather specifics a list of strings where each element is the actual **text** of a public SSH key.

The problem is that when no key IDs are specified in the API call to create a Packet device, Packet authorizes **all** the known keys in a project. This happens *in addition* to the keys we provision via Ignition. Passing an empty list [here](https://www.terraform.io/docs/providers/packet/r/device.html#project_ssh_key_ids) doesn't seem to help.

I suggest we do the following:

- Document the existing Packet behavior.
- Ask Packet to make it possible to toggle this behavior off.
- Add a workaround to Lokomotive (controlled by a knob if necessary) to allow switching this behavior off until a better solution exists.

One possible workaround is to disable the `coreos-metadata-sshkeys@core.service` service.

**Comment by invidian** [comment]
>Ask Packet to make it possible to toggle this behavior off.

We asked Packet about it some time ago, I poked them again today to see what's the status of it.

>One possible workaround is to disable the `coreos-metadata-sshkeys@core.service` service.

I would say we just implement that, this way we don't have to document anything. IMO adding a note in the changelog for existing cluster would be sufficient.

The reason we ask about SSH keys explicitly is that we don't take Packet integration into consideration, so I don't think we should be documenting it.
