### ISSUE TITLE
Rename `baremetal_0` to `t1.small.x86`

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#514]
In Packet docs and some places we use the term `baremetal_0` instead of `t1.small.x86`.

`baremetal_0` is not a well known term and a user can't look up for that on the internet.

**Comment by knrt10** [comment]
@surajssd if you don't mind I can take up this issue.

**Comment by surajssd** [comment]
Please do, I don’t mind at all.

**Comment by invidian** [comment]
Reopening, as #527 has been reverted in #642.

**Comment by invidian** [comment]
See also https://github.com/kinvolk/lokomotive/pull/642#issuecomment-647503208.

**Comment by invidian** [comment]
We use `c3.small.x86` as default now.
