### ISSUE TITLE
Remove documentation duplicates

### ISSUE THREAD

**Issue by iaguis** [kinvolk/lokomotive#52]
Once we have the [component configuration reference guides](https://github.com/kinvolk/lokomotive/pull/41), the howtos, and the quickstarts we should remove any documentation duplicates.

**Comment by invidian** [comment]
One PR up: https://github.com/kinvolk/lokomotive/pull/88

**Comment by invidian** [comment]
There are still 2 PRs with documentation opened:
- https://github.com/kinvolk/lokomotive/pull/80
- https://github.com/kinvolk/lokomotive/pull/77

I think once we have them merged, we should prepare a ToC for ducumentation and then remove the duplicates.

**Comment by invidian** [comment]
It looks to me that https://github.com/kinvolk/lokomotive/tree/master/docs/installer and https://github.com/kinvolk/lokomotive/tree/master/docs/quickstarts serves similar purpose. I wonder if we could/should somehow elaborate what are the differences.

**Comment by invidian** [comment]
I talked with @ipochi and he said he would like to take care of duplicates to ensure that no content is lost etc, so I'll just push some small changes I've done so far and move to a different task.

**Comment by ipochi** [comment]
https://github.com/kinvolk/lokomotive/pull/135

**Comment by iaguis** [comment]
https://github.com/kinvolk/lokomotive/pull/135 is merged. I think we can close this.
