### ISSUE TITLE
Packet docs provide taints and labels example

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#520]
The documentation for Packet and Labels does not mention anything how the input should be in the **Attribute reference** section.

https://github.com/kinvolk/lokomotive/blob/master/docs/configuration-reference/platforms/packet.md#attribute-reference

currently it just says 

![Screenshot from 2020-06-01 18-58-45](https://user-images.githubusercontent.com/5815795/83413761-02c8e480-a43a-11ea-90c3-655655f6e1c7.png)

**Comment by knrt10** [comment]
I am taking this if no one is working
