### ISSUE TITLE
Delete components in CI before destroying the cluster.

### ISSUE THREAD

**Issue by ipochi** [kinvolk/lokomotive#576]
We should be deleting the components in CI before destroying the cluster. This would increase the running time for a CI job but it also adds checks for `lokoctl component delete` which we currently do not have.

Another example is `external-dns` component which creates DNS entries for `dex` and `gangway` component. However as the cluster is destroyed, those DNS records are not deleted and accumulate. If we allowed component deletion before destroying the cluster, such accumulation of DNS records wouldn't happen.

**Comment by invidian** [comment]
>If we allowed component deletion before destroying the cluster, such accumulation of DNS records wouldn't happen.

In order to avoid accumulation to happen, we would have to ensure, that we don't shut down ExternalDNS until all records are removed, which is not trivial. But it will definitely help, as at least some records may get removed.

**Comment by ipochi** [comment]
> > If we allowed component deletion before destroying the cluster, such accumulation of DNS records wouldn't happen.
> 
> In order to avoid accumulation to happen, we would have to ensure, that we don't shut down ExternalDNS until all records are removed, which is not trivial. But it will definitely help, as at least some records may get removed.

I think if we delete the external-dns conponent last, then that should delete all the created dns records created by other components.

**Comment by ipochi** [comment]
Also the main point is e2e testing of `lokoctl component delete`. Clearing up DNS records would be the side benefit.

**Comment by knrt10** [comment]
@ipochi if you are not working, I can take a look into this.

**Comment by ipochi** [comment]
> @ipochi if you are not working, I can take a look into this.

Go ahead !! I am bit pre-occupied in NetworkPolicies.
