### ISSUE TITLE
Grafana Dashboard Kubernetes/StatefulSets: Shows StatefulSets from monitoring namespace only

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#579]
**Kubernetes/StatefulSets** in the following screenshot does not list any other namespaces:

![Screenshot from 2020-06-05 18-24-52](https://user-images.githubusercontent.com/5815795/83878683-281b6280-a75a-11ea-8cd0-f28a129d09cd.png)

**Comment by iaguis** [comment]
Maybe it's the only namespace with StatefulSets?

**Comment by iaguis** [comment]
One of my clusters has more StatefulSets in other namespaces and they show up there, so I think this works ok.

**Comment by surajssd** [comment]
Oh that is possible that this only shows that Statefulsets. And only volumes associated with statefulsets.

I will confirm it again in a bit and decide to close or keep it around.

**Comment by surajssd** [comment]
Oh yes you are right @iaguis I got confounded between this dashboard and the other one which only shows PV **Kubernetes/Persistent Volumes**.

**Comment by surajssd** [comment]
Sorry about the noise.
