### ISSUE TITLE
Grafana dashboard: "Kubernetes/Persistent Volumes" Gauge panel shows no data

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#587]
See following screenshot it shows `N/A`:

![Screenshot from 2020-06-09 14-25-23](https://user-images.githubusercontent.com/5815795/84128405-2bfefb80-aa5e-11ea-8606-2b501ce8794d.png)

**Comment by invidian** [comment]
Closing as #644 is closed as well.
