### ISSUE TITLE
Remove ExternalDNS contour ingress workaround

### ISSUE THREAD

**Issue by ipochi** [kinvolk/lokomotive#589]
Due to a long standing upstream issue of Contour (projectcontour/contour#403), we had to introduce a [workaround](https://github.com/kinvolk/lokomotive/commit/71c19e0bd7ed073a3010e5ffa4f17360dd6a5c45) for External DNS creating DNS entries.

Since the upstream issue has been resolved and released in the latest version of Contour, we should address the same in Lokomotive and find a graceful way to remove the workaround to avoid any breaking change.

**Comment by knrt10** [comment]
@ipochi can I work on this issue?

**Comment by ipochi** [comment]
@knrt10 Yes, please go ahead !!! Let me know if you have any questions :)
