### ISSUE TITLE
Deploying toolbox pod for rook ceph

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#594]
Toolbox is a pod that can be used as a cmd line interface to Ceph cluster deployed using rook. More info: https://rook.io/docs/rook/v1.3/ceph-toolbox.html.

Now this can be done in two ways:

- Just document how to do this by providing yaml file. The config looks like this: https://github.com/kinvolk/lokomotive/issues/585#issue-635127020
- Put it inside the rook component and deploy it if user specifies a flag in the component. If we do it as a part of the component then it will help us to reuse the tolerations and nodeaffinity.

**Comment by invidian** [comment]
Why do we need it? Isn't it part of generic rook ceph operations, which IMO is a bit out of scope of our project?
