### ISSUE TITLE
How is calico + metallb configured to not have conflicts in packet?

### ISSUE THREAD

**Issue by arianvp** [kinvolk/lokomotive#634]
Sorry if this is not the right place to enquire about this. I couldn't find some discussion forum related to Lokomotive.

I was messing around with calico + packet when I stumbled upon this project through Packet and saw that you provide a managed bare-metal kubernetes service on top of packet. cool!

I was building my cluster manually (without lokomotive) yesterday
I initally wanted to handle ingress traffic with Calico directly using https://www.projectcalico.org/advertising-kubernetes-service-ips-with-calico-and-bgp/

Namely Calico can directly advertise `ClusterIP`s to the BGP speaker; without the need for `type: LoadBalancer`.

Reason why I took this approach is because that's what Calico advertises; and seems conceptually a bit simpler.

However the downside is that `type: LoadBalancer` services in existing charts don't work; and people expect only `type: LoadBalancer` services to be exposed externally usually.

I tried setting up Metallb, but I stumbled upon https://metallb.universe.tf/configuration/calico/  which makes it sound like configuring it with Calico when you have just one ToR (which is the case in Packet) is complicated as metallb and calico can not be a speaker on the same link at the same time.

I was wondering how Lokomotive deals with this limiation, and made Calico+Metallb work at the same time?  I briefly scimmed through the code and documentation but couldn't find a clear answer.

**Comment by invidian** [comment]
Hey @arianvp, thanks for opening the issue. As far as I'm aware, we only use MetalLB to advertise the `ExternalIP` of the `Service` objects. The `ClusterIP` addresses are not being advertised, hence there is no conflict.

**Comment by arianvp** [comment]
Ah I think I understand now. It's only a conflict if you specifically use the external BGP peering option in Calico. But if you don't use that metallb works just fine. This helps.

I'll close it now as I think I grasp what's going on now.
