### ISSUE TITLE
Add lokoctl command to uninstall a component.

### ISSUE THREAD

**Issue by ipochi** [kinvolk/lokomotive#67]
Piping the output of `lokoctl render-manifest <component>` to `kubectl delete -f `or using helm to manage the components after installation is not the recommend way of managing components.

**Comment by ipochi** [comment]
Piping the output of `lokoctl render-manifest <component-name>` to `kubectl delete -f `or using helm to manage the components after installation is not the recommend way of managing components.

**Comment by iaguis** [comment]
The team agreed that it should be called `lokoctl component delete`.
