### ISSUE TITLE
Wrong copyright in assets_generate.go?

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#689]
https://github.com/kinvolk/lokomotive/blob/8e9c9943b54db5a29cf55167e0c12e30af205afc/pkg/assets/assets_generate.go#L1

If the code in this file was taken from another project (e.g. Prometheus), I believe the copyright notice should mention *both* that project and Lokomotive. If this is a mistake, we should fix it.

**Comment by invidian** [comment]
Yes, this code comes from prometheus project. We should add Lokomotive license too then.

**Comment by knrt10** [comment]
on it

**Comment by knrt10** [comment]
So I have a doubt, as both are `Apache License, Version 2.0`, should we add the whole license again or add like this

`Copyright 2018 The Prometheus Authors, Copyright 2020 The Lokomotive Authors` and rest of the remaining para?
