### ISSUE TITLE
Automated test of Lokomotive updates

### ISSUE THREAD

**Issue by iaguis** [kinvolk/lokomotive#695]
It would be useful to test Lokomotive updates automatically.

One idea is to take the last tagged release and try to update to latest master. Then we could run this test periodically.

**Comment by invidian** [comment]
Duplicate of #12?

**Comment by iaguis** [comment]
D'oh, I swear I searched!

**Comment by invidian** [comment]
I also couldn't find it under `updates`. But `update` did the trick and I remembered I did report it :smile:
