### ISSUE TITLE
Remove all usages of rkt

### ISSUE THREAD

**Issue by iaguis** [kinvolk/lokomotive#720]
rkt is not maintained anymore and keeping it is a security risk. We should remove it and replace it with something with equivalent functionality.

**Comment by invidian** [comment]
From #811 
>@alban had [a branch](https://github.com/kinvolk/lokomotive-kubernetes/pull/100/files) for this that can serve as a reference.

**Comment by vbatts** [comment]
Also, `rkt` will be deprecated from flatcar :smile_cat:

**Comment by arianvp** [comment]
Is this actually done? Lokomotive documentation mentions `rkt` still in many places; including in the update instructions:

https://kinvolk.io/docs/lokomotive/0.6/how-to-guides/update-bootstrap-kubelet/

**Comment by invidian** [comment]
Perhaps we could update the upgrade guide in 0.7 to not mention `rkt` anymore, we should've done it in 0.6.
