### ISSUE TITLE
Update MetalLB to latest autodiscovery patch

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#785]
Right now we use a patched version of MetalLB which was crafted from an early version of https://github.com/metallb/metallb/pull/593. The current version contains a bug which causes BGP sessions to flap in some cases.

Since it could take a while until https://github.com/metallb/metallb/pull/593 gets merged and released, we should update our patched version of MetalLB to the latest revision of the code in this PR.

Steps to perform:

- Create new images for the speaker and controller from https://github.com/metallb/metallb/pull/593.
- Push the images to `quay.io/kinvolk/metallb-speaker` and `quay.io/kinvolk/metallb-speaker`.
- Update the MetalLB manifests to the manifests from the latest revision (the upstream MetalLB manifests are changed in https://github.com/metallb/metallb/pull/593).

**Comment by johananl** [comment]
@iaguis please keep in mind I am currently refactoring https://github.com/metallb/metallb/pull/593 following https://github.com/metallb/metallb/pull/593#discussion_r463856330 and https://github.com/metallb/metallb/issues/682.

**Comment by iaguis** [comment]
Do you think we should wait until that work is finished or should we take the current state of the PR for now? I understand taking the current state means we'll need to do some more work in Lokomotive when the final feature is merged but I'd like to solve the flapping issue ASAP.

**Comment by johananl** [comment]
I think my latest refactoring as a better chance to solve the flapping sessions bug as it converges node peers with regular peers. I can likely finish the refactoring by EOD tomorrow.

**Comment by invidian** [comment]
PR #885 is up to fix this.
