### ISSUE TITLE
Move golangci-lint config to a file

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#786]
We should consider managing our `golangci-lint` configuration in a [file](https://golangci-lint.run/usage/configuration/#config-file).

Doing so has the following advantages:

- Should allow integrating with VS Code and other editors.
- Visually nicer than CLI arguments inside `Makefile`.

**Comment by invidian** [comment]
I had some issues with it, that some options were not possible via the config file, but I don't remember the details.

**Comment by johananl** [comment]
I assume we can combine, i.e. have most of the stuff in the config file. My main concern when opening this was being unable to integrate our linting rules with my IDE. It would save me a lot of time if I didn't have to run `make lint` to find problems.

**Comment by knrt10** [comment]
If no one is working on this, I can check it out

**Comment by johananl** [comment]
@knrt10 it's not assigned so go for it :-)
