### ISSUE TITLE
Update components of Lokomotive

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#790]
Update following components and terraform providers

| Done | Component            | Current Version      | Latest Version | Issue | PR   |
|------|----------------------|----------------------|----------------|-------|------|
|  :heavy_check_mark:  | `calico`             | `v3.15.0`            | `v3.15.2`      |    #836   |   #837 #841   |
|  :heavy_check_mark:     | `etcd`               | `v3.4.9`             | `v3.4.13`      |       | #783  #838|
|  :heavy_check_mark:   | `cert-manager`       | `v0.15.1`            | `v0.16.1`      |   #843    |   #847   |
|  :heavy_check_mark:    | `external-dns`       | `2.21.2`             | `3.3.0`        | #844      | #845     |
|      | `metallb`            | `v0.8.3-2-gf653773b` | `v0.9.3`       | #785  |      |
|  :heavy_check_mark:    | `rook`               | `v1.3.2`             | `v1.4.0`       |  #852     |   #879   |
|  :heavy_check_mark:  | `aws-ebs-csi-driver` | `0.5.0`              | `v0.6.0`       |   #854     |  #856   |
|   :heavy_check_mark:     | `velero`             | `2.7.0`              | `2.12.13`      |   #732    |    #830  |
|  :heavy_check_mark:  | `cluster-autoscaler` | `1.14.6`             | `1.18.1`       |   #858    |  #859   |

| Done | TF Provider | Current Version | Latest Version | Issue | PR   |
|------|-------------|-----------------|----------------|-------|------|
| :heavy_check_mark:     | Packet      | `2.7.3`         | `v3.0.0`       |    #834   | #835 |
| :heavy_check_mark:     | AWS         | `2.48.0`        | `v3.1.0`       |   #834    | #835 |
| :heavy_check_mark:     | Azure       | `1.35.0`        | `v2.22.0`      |    #834   | #835 |
| :heavy_check_mark:     | TLS         | `2.0`           | `v2.2.0`       |    #834   | #835 |
| :heavy_check_mark:     | Local       | `1.2`           | `v1.4.0`       |   #834    | #835 |
| :heavy_check_mark:     | Null        | `2.1`           | `v2.1.2`       |    #834   | #835 |
| :heavy_check_mark:     | CT          | `0.5.0`         | `v0.6.1`       |    #834   | #835 |
| :heavy_check_mark:     | Matchbox    | `0.3`           | `v0.4.1`       |    #834   | #835 |

**Comment by knrt10** [comment]
I think we should divide this issue, because updating all at the same time would be difficult. Creating sub-issues would be nice, what do you think?

**Comment by surajssd** [comment]
@knrt10 feel free to create those issues for tracking purposes. But I feel some components update work is very trivial that creating issue for them will just be additional overhead.

**Comment by knrt10** [comment]
Cool, I think done column will come to use for this then.

**Comment by invidian** [comment]
Linked some issues and PRs in the table.

**Comment by ipochi** [comment]
Divide and Conquer. 

This task has progressing nicely. Kudos :tada:

**Comment by invidian** [comment]
As MetalLB is part of the v0.4.0 milestone and it's a last component to update, I'll close this issue. Good work everyone :boom:
