### ISSUE TITLE
Bump Grafana version to 7.1.0

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#792]
Update the Grafana version to the latest in the `prometheus-operator` chart. This can be changed here:
https://github.com/kinvolk/lokomotive/blob/919924ed3b0e652b29a50f9f9a3f59c6be7bdcfb/assets/components/prometheus-operator/manifests/requirements.yaml#L13-L16 
and 
https://github.com/kinvolk/lokomotive/blob/919924ed3b0e652b29a50f9f9a3f59c6be7bdcfb/assets/components/prometheus-operator/manifests/requirements.lock#L8-L10.

Find the latest version of Grafana chart here: https://github.com/helm/charts/blob/master/stable/grafana/Chart.yaml.

**Comment by invidian** [comment]
Looks reasonable I guess. Some related upstream PR: https://github.com/helm/charts/pull/23347 ?
