### ISSUE TITLE
Tighten firewall rules during node boot window

### ISSUE THREAD

**Issue by iaguis** [kinvolk/lokomotive#8]
When a new node is created, it starts with a basic set of firewall rules before getting full dynamic firewall rules from the Kubernetes control plane.

There is a small (few minutes) window while the node starts where the basic firewall rules have been applied and the node is internet exposed more broadly than it could be. We should lock down the exposed ports to just the cluster IP range earlier in the boot process so that the exposure is reduced.

**Comment by johananl** [comment]
Summarizing the remaining work items:

- [ ] Verify the rules we currently have in the "pre-Calico policy" are tight enough. Can we lock things down even more?
- [ ] Consider adding the functionality we have on Packet also on bare metal. Is it indeed necessary considering the fact that on-premise bare metal likely won't be exposed to the internet? If so, what default policy should we use for bare metal?
- [ ] Run a test in which we continually poke relevant ports on cluster nodes during cluster bootstrap to verify we have no "holes".
- [ ] Run a test in which we check for "holes" during failure scenarios. For example, are we exposed if Calico is down?

**Comment by invidian** [comment]
> Verify the rules we currently have in the "pre-Calico policy" are tight enough. Can we lock things down even more?

As far as I know, yes. Our current policies opens ports for both public and private interfaces for example. We should tight that. We could also use management CIDRs when creating them.

**Comment by invidian** [comment]
PR opened for this: #202.

**Comment by invidian** [comment]
#202 is now merged.

**Comment by iaguis** [comment]
Let's close this then. I think bootstrap rules are tight enough now.
