### ISSUE TITLE
Investigate alternatives to Velero component for backup and restore of stateful workloads in Lokomotive clusters 

### ISSUE THREAD

**Issue by ipochi** [kinvolk/lokomotive#800]
Investigate the continued usage of Velero as an official supported component for backup and restore
Investigate and propose any alternatives.

**Comment by invidian** [comment]
@ipochi mind writing down the conclusion? Which alternative solutions did you test or why the alternatives has been rejected?

**Comment by ipochi** [comment]
Sure
