### ISSUE TITLE
deprecate rkt

### ISSUE THREAD

**Issue by vbatts** [kinvolk/lokomotive#811]
As `rkt` upstream is now archived, let's switch to systemd-nspawn and/or docker.

[@alban had a branch](https://github.com/kinvolk/lokomotive-kubernetes/pull/100/files) for this that can serve as a reference.

**Comment by invidian** [comment]
I'll close as a duplicate of #720.

**Comment by vbatts** [comment]
weird that didn't show up when i searched for "rkt" :thinking: 
thanks tho
