### ISSUE TITLE
Add contributing guidelines and contributor docs

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#82]
Provide general guidelines and docs on how to find `low-hanging-fruit`, `easy-first` issues, how to clone the repo and getting started, etc.

**Comment by invidian** [comment]
We already have https://github.com/kinvolk/lokomotive/blob/master/docs/CONTRIBUTING.md.

**Comment by surajssd** [comment]
I think that needs update, they look kinda archaic.

**Comment by invidian** [comment]
Perhaps should be moved to top directory too, to follow GitHub convention.

**Comment by ipochi** [comment]
@surajssd @invidian 

I think this can be closed as some work was done to improving the contribution doc and also Joaquim added a Kinvolk Code of Conduct document to go along with the contribution document.
