### ISSUE TITLE
Add back the `external_url` in the prometheus block

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#826]
Remove this overriding of the `ingress.host` as it is done here:
https://github.com/kinvolk/lokomotive/blob/df2951c331bba1190474aec00d403fedcccec54a/pkg/components/prometheus-operator/template.go#L119-L121

Add back the dedicated `external_url` to the `prometheus` block, like it is done for the alertmanager.

**Comment by johananl** [comment]
@surajssd can this be closed before the next sprint?

**Comment by surajssd** [comment]
@johananl yep the PR is open, PTAL https://github.com/kinvolk/lokomotive/pull/964
