### ISSUE TITLE
Make Terraform code accept taints and labels in complex type, not as string

### ISSUE THREAD

**Issue by invidian** [kinvolk/lokomotive#833]
So we keep flexible format for longer and we can do the formatting to string on Terraform template level.

**Comment by knrt10** [comment]
Related or duplicate of https://github.com/kinvolk/lokomotive/issues/489

**Comment by invidian** [comment]
>Related or duplicate of #489

Related indeed, but #489 is about Go code and this one is about Terraform modules.
