### ISSUE TITLE
Fix linting issues

### ISSUE THREAD

**Issue by knrt10** [kinvolk/lokomotive#882]
There are a lot of linter warnings that are not fixed. For example just in `cli` folder. We should fix for whole lokomotive repo.

![linter issues](https://user-images.githubusercontent.com/24803604/91686921-235d2380-eb7c-11ea-92c2-17a369e268c6.png)

**Comment by invidian** [comment]
A duplicate of #537.

**Comment by knrt10** [comment]
Closing this in favor of that
