### ISSUE TITLE
Ensure that controlplane pods are spread equally across controller nodes

### ISSUE THREAD

**Issue by invidian** [kinvolk/lokomotive#90]
`kube-controller-manager` and `kube-scheduler` use Deployment object with `preferredDuringSchedulingIgnoredDuringExecution`, which means that during scheduling, pods will be equally spread across nodes. However, if there is only one controller node available during bootstrapping (it does happen, as nodes join without particular order), then all pods are getting scheduled on this single node. If this node fails, then the entire controlplane goes down, which gives user a false sense of redundancy of the controlplane.

We should ensure, that those pods are always scheduled equally across nodes to maximize the redundancy.

One way of achieving that would be to use `requiredDuringSchedulingIgnoredDuringExecution` instead of `preferredDuringSchedulingIgnoredDuringExecution`, however that has negative effect when having just a single controlplane node, that more than one pod cannot be scheduled on a single node, and that is recommended for doing upgrades, so we would have to do that conditionally.

The alternative would be to use [descheduler](https://github.com/kubernetes-sigs/descheduler), which would periodically ensure, that pods are spread.

Currently for `kube-apiserver` we use DaemonSet, which makes sure that their pods are equally spread across controller nodes, but might be changed to `Deployment` as well, if #32 gets merged.

**Comment by surajssd** [comment]
A simple podAntiAffinity will help as well to broaden this spread.

**Comment by invidian** [comment]
#1030 changed controlplane components to be deployed as DaemonSets in HA setup, so this is ensured. However, we may need to roll it back because of #1097.

**Comment by surajssd** [comment]
I think #1097 specifies a code that should have been cleaned up in #1030 itself. Why should the fix be to revert and not fix this https://github.com/kinvolk/lokomotive/blob/c73006679aa69de0a67adbb4eafd22cbfade1444/assets/terraform-modules/bootkube/assets.tf#L72 ?

**Comment by invidian** [comment]
>I think #1097 specifies a code that should have been cleaned up in #1030 itself. Why should the fix be to revert and not fix this

If I understand you correctly, then yes, possibly fixing this Terraform code should be sufficient ot fix #1097. Then this can be closed as well I think.
