### ISSUE TITLE
`delete-node.service` cannot access `kubeconfig` when using tls bootstrap

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#917]
Here is the script that runs under in `delete-node.service`:

https://github.com/kinvolk/lokomotive/blob/eab6cbc45fd2b6ae30a2641806bb16303656e885/assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl#L134-L154

As you can see only one volume is mounted here `/etc/kubernetes` and not the `/var/lib/kubelet/` so kubectl will fail in such a case.

**Comment by invidian** [comment]
Does #946 address that?

**Comment by surajssd** [comment]
@invidian yes.
