### ISSUE TITLE
Makefile: add unit tests, compiling all tests and running linter to default target

### ISSUE THREAD

**Issue by invidian** [kinvolk/lokomotive#93]
So just running `make` runs all possible tests.

Part of this is #44

**Comment by iaguis** [comment]
Not sure I like doing this as part of the default make target, I usually want make to run as fast as possible. Maybe a git hook is better?

**Comment by invidian** [comment]
>Not sure I like doing this as part of the default make target, I usually want make to run as fast as possible. Maybe a git hook is better?

Only the first run would be slow, consecutive runs should be a matter of seconds. From my tests, it takes ~5 seconds for consecutive runs and when I changed single line of code, it took 8 seconds.

But the issue is actually about having some target which triggers all that, I don't mind having it as for example `make all`. Default target would be just for convenience, so when you do any code change, you should do just `make`.
