### ISSUE TITLE
Increase the rook-ceph-operator memory limits

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#932]
Right now the operator pod has limit of 256Mi which can be limiting and pod goes into a OOMKill spiral. Increase the memory limit to 500Mi.

**Comment by johananl** [comment]
I'm wondering if we should just increase the value statically or expose the requests/limits in the config. If we do the latter, we should probably do it for *all* components since this is a generic problem rather than Rook-specific.
