### ISSUE TITLE
Add test to verify the functionality of flatcar-linux-update-operator

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#959]
Add a upgrade test to verify if this actually updates the cluster machines, gracefully.

**Comment by invidian** [comment]
Notes:
- Currently we disable updates on Packet as they were installing older versions which was causing nodes to reboot while running e2e tests.
- We would need to deploy older version of Flatcar everywhere to test updates.
- FLUO pipeline could test that.
- Those tests should be marked as e2e disruptive or we should have a separate, tainted worker pool to test this.

**Comment by iaguis** [comment]
Closing in favor of #1000
