### ISSUE TITLE
Metallb: Test if it works with private EIP on Packet

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#960]
Right now metallb has been primarily worked with public EIP of Packet cloud. Test if this works with private EIP as well.

In cases when a user wants to expose app internal to the Packet project they can do so using private EIP. Also private EIPs can be abundant that they can be directly used by apps using Loadbalancer service, instead of adding an extra hop of an ingress controller.

cc: @johananl

**Comment by johananl** [comment]
I've tested this using an unused address from the project's `/25` private CIDR. Seems to work fine. The user would need to find a proper way to allocate private addresses though as the Packet console doesn't seem to offer this functionality.

**Comment by surajssd** [comment]
@johananl should we close this or should we just convert it into a documentation issue?

**Comment by johananl** [comment]
I'd close this. The intention was to verify private addresses aren't a special case (and they aren't).
Is there something specific you would document @surajssd?

**Comment by surajssd** [comment]
We ask user to use public EIP, but we don't say anywhere that private IPs on Packet work as well. I just want to highlight that.

**Comment by invidian** [comment]
If this works, we should change the documentation, as currently we say Public EIP: https://github.com/kinvolk/lokomotive/blob/master/docs/how-to-guides/ingress-with-contour-metallb.md#prerequisites.

**Comment by johananl** [comment]
Private IPs work but there is no official way to request a private block for BGP on Packet. I'm not sure we want to encourage users to do something that isn't officially supported.

**Comment by invidian** [comment]
Ah, thanks for clarification @johananl. I'll leave it up to @surajssd to decide if we can close it then.

**Comment by surajssd** [comment]
Alright then closing it.
