### ISSUE TITLE
Documentation for external-dns doesn't match behavior

### ISSUE THREAD

**Issue by marga-kinvolk** [kinvolk/lokomotive#995]
https://github.com/kinvolk/lokomotive/blob/master/docs/configuration-reference/components/external-dns.md lists `aws.aws_access_key_id` and `aws.aws_secret_access_key` as valid fields, but trying to apply a configuration that includes them fails with:

```
$ lokoctl component  apply external-dns --lokocfg-vars lokocfg-vars 
Applying component 'external-dns'...
routing.lokocfg:29,28-46: Unsupported attribute; This object does not have an attribute named "aws_access_key_id"., and 3 other diagnostic(s)
FATA[0000] routing.lokocfg:29,28-46: Unsupported attribute; This object does not have an attribute named "aws_access_key_id"., and 3 other diagnostic(s)  args="[external-dns]" command="lokoctl component apply"
```

I guess these fields were removed (the config used to work with a previous lokomotive version) but the documentation didn't get updated?

**Comment by invidian** [comment]
hmm, we didn't touch those fields any time recently. @marga-kinvolk can you please share some snippet of `routing.lokocfg` file or tell us on which version it worked? You can do a noop run using `lokoctl component render-manifest external-dns`, which should process the configuration.

**Comment by marga-kinvolk** [comment]
This is the config that wasn't working:

```
component "external-dns" {
  # Required arguments.
  owner_id = "external-dns"
  aws {
    # Required arguments
    zone_type = "public"
    zone_id = var.aws_zone_id
    # Optional arguments.
    aws_access_key_id = var.aws_access_key_id
    aws_secret_access_key = var.aws_secret_access_key
  }

  # Optional arguments.
  sources = ["ingress"]
  namespace = "external-dns"
  policy = "upsert-only"

  # Monitor this service with Prometheus Operator
  metrics = true
}
```

I commented out the two aws fields and it worked.  I created this config using loko 0.2.1 and it was working fine then. It broke when trying to apply loko 0.3.0.

**Comment by invidian** [comment]
Hmm, I think the misleading error message might be caused because `aws_access_key_id` is either not declared or it has no value set, could you check that too?

**Comment by marga-kinvolk** [comment]
You are indeed right. I guess in some refactoring I deleted the `aws_access_key_id` and `aws_secret_access_key` fields from my `lokocfg.vars` file.

routing.lokocfg has this:

```
variable "aws_zone_id" { }
variable "aws_access_key_id" { }
variable "aws_secret_access_key" { }
```

But only the zone_id is defined in `lokocfg.vars`.

Ok, I guess in that case the error should have been that the variable is empty and an empty value is not allowed?

**Comment by invidian** [comment]
>Ok, I guess in that case the error should have been that the variable is empty and an empty value is not allowed?

~Yes, you're right. I think we should create new issue to improve this error message and link to this issue (so this one can be closed, to sort of archive this context). What do you think?~

Yes, you're right. We actually have an issue for it already: #699. Do you mind if I close this one then?

**Comment by marga-kinvolk** [comment]
Sure, let's close as a duplicate of #699
